### ISSUE TITLE
bug: dap error in java file

### ISSUE THREAD

**Issue by nyjackie** [nvim-java/nvim-java#103]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.4

### Operating system/version

MacOS 14.2.1

### Describe the bug

dap encounters error running java class file: [video demonstration](https://www.youtube.com/watch?v=OsGH3st8mlM)

### Steps To Reproduce

1. install nvim-java and necessary dependencies.
2. run java file.

### Expected Behavior

dap does not encounters error.

**Comment by s1n7ax** [comment]
I see. It's due to the file you have opened is not being a gradle/maven/eclipse project. However, sounds like this is something we should be able to debug. I will look into it. BTW, you can drag and drop videos to the issue.

**Comment by soeguet** [comment]
This might help:

opening up neovim will invoke and fail via mason:
`
Downloading file "https://open-vsx.org/api/vscjava/vscode-java-debug/0.52.0/file/vscjava.vscode-java-debug-0.52.0.vsix"…
`

but if you press i yourself this will be invoked and succeed:
`
▶ # [2/2] Downloading file "https://open-vsx.org/api/vscjava/vscode-java-debug/0.55.0/file/vscjava.vscode-java-debug-0.55.0.vsix"…
`

**Comment by VICTORVICKIE** [comment]
I am encountering similar issue, but also it seems DAP configuration fails too

```shell
dap configuration failed
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
stack traceback:
^I...cal/nvim-data/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
^I...m-data/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
^I...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
^I...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:1393: in function 'cb'
^Ivim/_editor.lua:263: in function <vim/_editor.lua:262>                                                                                                                                                                                    Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...cal/nvim-data/lazy/nvim-java/lua/java/handlers/error.lua:28:
dap configuration failed
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
stack traceback:
        ...cal/nvim-data/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
        ...m-data/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
        ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'                                                                                                                                                       ...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:1393: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>
stack traceback:
        [C]: in function 'error'
        ...cal/nvim-data/lazy/nvim-java/lua/java/handlers/error.lua:28: in function 'error_handler'
        ...m-data/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
        ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
        ...p/apps/neovim/current/share/nvim/runtime/lua/vim/lsp.lua:1393: in function 'cb'
        vim/_editor.lua:263: in function <vim/_editor.lua:262>                       
```

https://github.com/VICTORVICKIE/dotfiles/blob/main/nvim/lua/plugins/mason-lsp-config.lua

Please suggest if the lsp plugin needs to be setup differently

**Comment by nyjackie** [comment]
> I see. It's due to the file you have opened is not being a gradle/maven/eclipse project. However, sounds like this is something we should be able to debug. I will look into it. BTW, you can drag and drop videos to the issue.

Thank you for looking into this. and thank you for the hard works 💪 
PS: my video size was too large 😢

**Comment by s1n7ax** [comment]
@nyjackie https://handbrake.fr/ You are welcome.

**Comment by s1n7ax** [comment]
@VICTORVICKIE This is not related to nvim-java but you can fix it by updating `mason.nvim`. However, after update, you might face this issue. Please leave a comment if so.

https://github.com/nvim-java/nvim-java/issues/104

**Comment by distractedpen** [comment]
@s1n7ax Yes, this issue was actually the first issue that I encountered before #104. Updating mason did fix this issue (as they added openvsx download support in version 1.9.0), but then I started getting #104.

**Comment by s1n7ax** [comment]
@distractedpen are you saying that #104 is not fixed?

**Comment by distractedpen** [comment]
No issues anymore after updating, sorry for the confusion.

**Comment by marvindore** [comment]
I am running Mason version v1.9.0 and have the following installed `java-debug-adapter, java-test, jdtls`. Dap does not automatically configure so I run the `JavaDapConfig` command and get the following error:

```
Configuring DAP

dap configuration failed
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
stack traceback:
^I...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
^I...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
^I...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
^I....mount_nvimQLxuJP/usr/share/nvim/runtime/lua/vim/lsp.lua:1517: in function ''
^Ivim/_editor.lua: in function <vim/_editor.lua:0>
Error executing vim.schedule lua callback: ...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: 
dap configuration failed
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
stack traceback:
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
	...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
	....mount_nvimQLxuJP/usr/share/nvim/runtime/lua/vim/lsp.lua:1517: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
	[C]: in function 'error'
	...al/share/nvim/lazy/nvim-java/lua/java/handlers/error.lua:28: in function 'error_handler'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
	...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
	....mount_nvimQLxuJP/usr/share/nvim/runtime/lua/vim/lsp.lua:1517: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

**Comment by erlonbie** [comment]
same issue as @marvindore with all plugins updated

**Comment by erlonbie** [comment]
@marvindore I found the in your [config](https://github.com/marvindore/.dotfiles/blob/fcb80e5b6f47d54df9b3f0c43f5acae4df2b8d71/nvim/lua/plugins/nvim-java.lua#L21)  the config function should be outside `dependencies`. I puted:

    require('java').setup()
    require('lspconfig').jdtls.setup({})

inside it and it fixed.

**Comment by marvindore** [comment]
@erlonbie thank you so much! I didn't even noticed I misplaced that Curley brace. I haven't been working on Java lately but will try that out on my next Java project.

**Comment by manumoreno** [comment]
Hey guys, I've been facing the same issue for some time. As a result, dap is not working as expected and the springboot lsp does not start either. Any ideas on how to get around this problem?

**Comment by chetra-seng** [comment]
@manumoreno I found a fix here. Try it and let me know :)
https://github.com/nvim-java/nvim-java/issues/104#issuecomment-2558705104

**Comment by s1n7ax** [comment]
You can now change the versions in the config itself.
https://github.com/nvim-java/nvim-java?tab=readme-ov-file#wrench-configuration

Note: the version combination looks broken right now for testing. I'm not sure which caused it. If you find version combination that works, let me know.
