### ISSUE TITLE
feature: lint & style check tasks to Makefile

### ISSUE THREAD

**Issue by s1n7ax** [nvim-java/nvim-java#108]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

https://github.com/orgs/nvim-java/discussions/102

### Describe the solution you'd like

-

### Describe alternatives you've considered

-

### Additional context

-

**Comment by atm1020** [comment]
@s1n7ax  can i work on this issue ?

**Comment by s1n7ax** [comment]
@atm1020 I'm creating issues for everything just so I don't forget & easy to track. Pick any task you want, when ever you want. There is no deadline so finish it when ever you want. Let me know when you start working on this to change the status so others know this is being worked on.

**Comment by s1n7ax** [comment]
@atm1020 Congrats! You make your first commit :)

![image](https://github.com/nvim-java/nvim-java/assets/18459807/e10698bd-c743-4e92-ac72-a068a698b5a1)
