### ISSUE TITLE
Mason fails to install java-debug-adapter

### ISSUE THREAD

**Issue by AlexandreBrg** [nvim-java/nvim-java#111]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

Fedora 39

### Describe the bug

Hello! 

I tried to install this plugin, all plugins managed to properly be installed except one: `java-debug-adapter`. On mason side, I only have the following logs, they show up everytime I run neovim:

![image](https://github.com/nvim-java/nvim-java/assets/23573685/0e212dfa-7cf9-4bab-a750-bd511945333a)

### Steps To Reproduce

I followed install steps by adding `require('java').setup {}` and `jdtls` to lspconfig.

### Expected Behavior

.

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-unknown-purl-type-openvsx
