### ISSUE TITLE
Does not work in a gradle project bug: 

### ISSUE THREAD

**Issue by MxDx** [nvim-java/nvim-java#124]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5 Build type: Release LuaJIT 2.1.1702233742

### Operating system/version

Archlinux 6.7

### Describe the bug

I installed the plugin with LazyVim using the provided instructions, but when I arrive on my gradle project the plugin launch but once it has started I have errore everywhere as if  my code is wrong even though it is just a hello world in java. The java.utils package are marked as not recognise, String cannot be resolved to a type, etc. What it is weird is the fact that it provide autocompletion but in the ui have error and I cannot launch using JavaTestRunCurrent... It throws error

### Steps To Reproduce

Opening a simple java file

### Expected Behavior

I expect it to work and that i can be able to launch using JavaTestRunCurrentClass on a gradle project
![image](https://github.com/nvim-java/nvim-java/assets/75937961/e6eef6de-949a-451d-ae19-0e0c08849dce)

**Comment by s1n7ax** [comment]
@MxDx Is this still the case? Could you please re-open the issue and send the logs. It's in `~/.local/share/nvim` location. `nvim-java.log` & `nvim-java-core.log`
