### ISSUE TITLE
feature: Run an application with an active profile set

### ISSUE THREAD

**Issue by garrettkrohn** [nvim-java/nvim-java#131]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I cannot figure out how to run an application with an active profile, as a result it cannot configure correctly and I have to do all of my debugging in Intellij instead of Neovim.  I have looked around for a solution, but haven't been able to find one.

### Describe the solution you'd like

It would be great to have a parameter available at setup to pass in an active profile name.

### Describe alternatives you've considered

I've tried setting up an environment variables with no luck, and I've tried digging through your code to find where the configuration happens and I was unable to, my lua is very weak.

### Additional context

Thank you so much for your work on this repo, I use it every day for work and it is fantastic!

**Comment by s1n7ax** [comment]
@garrettkrohn Now you can create profiles using `JavaProfile` command.

https://github.com/nvim-java/nvim-java?tab=readme-ov-file#profiles

**Comment by garrettkrohn** [comment]
<img width="855" alt="Screenshot 2024-04-13 at 8 55 34 PM" src="https://github.com/nvim-java/nvim-java/assets/104032851/d6ace282-fc24-447c-8a15-140d0f3e0eb1">
Thank you for adding this!  I'm getting this error when trying to run the `JavaProfile` command, I'll do some digging and see if I can figure out what the issue is.

**Comment by s1n7ax** [comment]
@garrettkrohn Jdtls has some commands we can execute. This exact one being added by jdtls plugin we load. This basically means plugin has not loaded. You happened to have nvim-jdtls installed? If so remove that. I might be able to help you if you have the config on github

**Comment by garrettkrohn** [comment]
I don't have `nvim-jdtls` installed, but I have jdtls installed via mason.  Here are my dotfiles: https://github.com/garrettkrohn/dotfiles

**Comment by s1n7ax** [comment]
@garrettkrohn You somehow have to call `java.setup()` before `jdtls.setup()`. Try this.

Delete this line where you setup jdtls LS.
https://github.com/garrettkrohn/dotfiles/blob/b710efb164344a49fced0790c6e8766cda2b4d18/config/nvim/lua/config/lazy.lua#L320

And paste it inside this function but after nvim-java setup
https://github.com/garrettkrohn/dotfiles/blob/b710efb164344a49fced0790c6e8766cda2b4d18/config/nvim/lua/config/lazy.lua#L264-L266

Should look as follows.
```lua
["jdtls"] = function()
    require("java").setup()
    require("lspconfig").jdtls.setup({})
end,
```

**Comment by garrettkrohn** [comment]
@s1n7ax Thank you so much, I should have mentioned I use `kickstart` folder in that repository, but I was able to take what you said and get the profile ui up and running.  Really appreciate the assistance.  This will help me be far more productive at work!

**Comment by garrettkrohn** [comment]
Please ignore the above comment, I did not have the VM Arguments set correctly.  Thank you so much for your help and your work on this plugin!!

**Comment by s1n7ax** [comment]
@garrettkrohn Is it safe to use the config as instruction to install nvim-java on kickstarter?

```lua
{
  "nvim-java/nvim-java",
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        handlers = {
          ["jdtls"] = function()
            require("java").setup()
            require("lspconfig").jdtls.setup({})
          end,
        },
      },
    },
  },
}
```

**Comment by garrettkrohn** [comment]
@s1n7ax I believe so, looking through my config and I don't there there is anything other than what you have pasted above!  Do you want me to add that to the readme in a pr?

**Comment by s1n7ax** [comment]
@garrettkrohn We have lazyvim instruction in wiki and I have a link to that in readme. If you can do the same please go ahead.

https://github.com/nvim-java/nvim-java/wiki

**Comment by garrettkrohn** [comment]
@s1n7ax Sorry, I tried to figure out how to edit the wiki and was unable to.  I wish the Wiki was just a folder in the repo.
