### ISSUE TITLE
feature: Example adding this to kickstart.nvim

### ISSUE THREAD

**Issue by ctrlplusb** [nvim-java/nvim-java#132]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I've tried adding this to kickstart.nvim, but think there are issues with the way they set up lsp and dap which might be conflicting with the internals of your plugin.

### Describe the solution you'd like

An example of adding the plugin to kickstart would be amazing.

### Describe alternatives you've considered

I've been looking at the internals to try and understand some of the config. Was wondering if your plugin could be decomposed somewhat, so that you have the full `require('java').setup()` flow, and then also the capability to import and compose the lsp, dap, etc configurations in more isolation to add into existing lsp/dap configs. Hope that makes sense.

**Comment by vaesbart** [comment]
Maybe related, since I also use kickstart -- I tried to install this plugin and set config to use my current JDK but unsuccesfull so far.
It keeps downloading openjdk-17 - I'm guessing because of lombok plugin ?

For reference; my config:
<pre>
return {
  'nvim-java/nvim-java',
  dependencies = {
    'nvim-java/lua-async-await',
    'nvim-java/nvim-java-core',
    'nvim-java/nvim-java-test',
    'nvim-java/nvim-java-dap',
    'MunifTanjim/nui.nvim',
    'neovim/nvim-lspconfig',
    'mfussenegger/nvim-dap',
    {
      'williamboman/mason.nvim',
      opts = {
        registries = {
          'github:nvim-java/mason-registry',
          'github:mason-org/mason-registry',
        },
      },
    },
  },
  config = function()
    require('java').setup {}
    require('lspconfig').jdtls.setup {
      settings = {
        java = {
          configuration = {
            runtimes = {
              {
                name = 'OpenJDK-22',
                path = '/usr/lib64/jvm/java-22-openjdk-22',
                default = true,
              },
            },
          },
        },
      },
    }
  end,
}
</pre>

**Comment by s1n7ax** [comment]
@vaesbart Try this.

```lua
require('java').setup({
	jdk = {
		auto_install = false,
	},
})
```

**Comment by vaesbart** [comment]
Yes that seems to have fixed it , thanks.

**Comment by zMynxx** [comment]
> Maybe related, since I also use kickstart -- I tried to install this plugin and set config to use my current JDK but unsuccesfull so far. It keeps downloading openjdk-17 - I'm guessing because of lombok plugin ?
> 
> For reference; my config:
> 
> return {
>   'nvim-java/nvim-java',
>   dependencies = {
>     'nvim-java/lua-async-await',
>     'nvim-java/nvim-java-core',
>     'nvim-java/nvim-java-test',
>     'nvim-java/nvim-java-dap',
>     'MunifTanjim/nui.nvim',
>     'neovim/nvim-lspconfig',
>     'mfussenegger/nvim-dap',
>     {
>       'williamboman/mason.nvim',
>       opts = {
>         registries = {
>           'github:nvim-java/mason-registry',
>           'github:mason-org/mason-registry',
>         },
>       },
>     },
>   },
>   config = function()
>     require('java').setup {}
>     require('lspconfig').jdtls.setup {
>       settings = {
>         java = {
>           configuration = {
>             runtimes = {
>               {
>                 name = 'OpenJDK-22',
>                 path = '/usr/lib64/jvm/java-22-openjdk-22',
>                 default = true,
>               },
>             },
>           },
>         },
>       },
>     }
>   end,
> }

I using the modular [version of Kickstart ](https://github.com/dam9000/kickstart-modular.nvim) and I'm having real difficulties. I've taken it's [debug.lua](https://github.com/dam9000/kickstart-modular.nvim/blob/master/lua/kickstart/plugins/debug.lua) and tried adding the configuration you've provided, using mostly defaults.
Here's where I'm at

```lua
-- debug.lua
--
-- shows how to use the dap plugin to debug your code.
--
-- primarily focused on configuring the debugger for go, but can
-- be extended to other languages as well. that's why it's called
-- kickstart.nvim and not kitchen-sink.nvim ;)

return {
  -- note: yes, you can install new plugins here!
  'mfussenegger/nvim-dap',
  -- note: and you can specify dependencies as well
  dependencies = {
    -- creates a beautiful debugger ui
    'rcarriga/nvim-dap-ui',

    -- required dependency for nvim-dap-ui
    'nvim-neotest/nvim-nio',

    -- installs the debug adapters for you
    'williamboman/mason.nvim',
    'jay-babu/mason-nvim-dap.nvim',

    -- add your own debuggers here
    'nvim-java/nvim-java',
    'nvim-java/lua-async-await',
    'nvim-java/nvim-java-core',
    'nvim-java/nvim-java-test',
    'nvim-java/nvim-java-dap',
    'MunifTanjim/nui.nvim',
    'neovim/nvim-lspconfig',
  },
  config = function()
    local dap = require 'dap'
    local dapui = require 'dapui'
    --- Added to overcome 'no configurations found for `java` error'
    dap.configurations.java = {
      {
        javaExec = 'java',
        request = 'launch',
        type = 'java',
      },
      {
        type = 'java',
        request = 'attach',
        name = 'Debug (Attach) - Remote',
        hostName = '127.0.0.1',
        port = 5005,
      },
    }

    require('mason-nvim-dap').setup {
      -- makes a best effort to setup the various debuggers with
      -- reasonable debug configurations
      automatic_setup = true,

      -- you can provide additional configuration to the handlers,
      -- see mason-nvim-dap readme for more information
      handlers = {},

      -- you'll need to check that you have the required things installed
      -- online, please don't ask me how to install them :)
      ensure_installed = {
        -- update this to ensure that you have the debuggers for the langs you want
        'java-debug-adapter',
      },
    }

    -- basic debugging keymaps, feel free to change to your liking!
    vim.keymap.set('n', '<f5>', dap.continue, { desc = 'debug: start/continue' })
    vim.keymap.set('n', '<f1>', dap.step_into, { desc = 'debug: step into' })
    vim.keymap.set('n', '<f2>', dap.step_over, { desc = 'debug: step over' })
    vim.keymap.set('n', '<f3>', dap.step_out, { desc = 'debug: step out' })
    vim.keymap.set('n', '<leader>b', dap.toggle_breakpoint, { desc = 'debug: toggle breakpoint' })
    vim.keymap.set('n', '<leader>B', function()
      dap.set_breakpoint(vim.fn.input 'breakpoint condition: ')
    end, { desc = 'debug: set breakpoint' })

    -- dap ui setup
    -- for more information, see |:help nvim-dap-ui|
    dapui.setup {
      -- set icons to characters that are more likely to work in every terminal.
      --    feel free to remove or use ones that you like more! :)
      --    don't feel like these are good choices.
      icons = { expanded = '▾', collapsed = '▸', current_frame = '*' },
      controls = {
        icons = {
          pause = '⏸',
          play = '▶',
          step_into = '⏎',
          step_over = '⏭',
          step_out = '⏮',
          step_back = 'b',
          run_last = '▶▶',
          terminate = '⏹',
          disconnect = '⏏',
        },
      },
    }

    -- toggle to see last session result. without this, you can't see session output in case of unhandled exception.
    vim.keymap.set('n', '<f7>', dapui.toggle, { desc = 'debug: see last session result.' })

    dap.listeners.after.event_initialized['dapui_config'] = dapui.open
    dap.listeners.before.event_terminated['dapui_config'] = dapui.close
    dap.listeners.before.event_exited['dapui_config'] = dapui.close

    -- install golang specific config
    require('java').setup {}
    require('lspconfig').jdtls.setup {
      settings = {
        java = {
          configuration = {
            runtimes = {
              -- Use default to ease getting started
              -- { 
              --   name = 'OpenJDK-22',
              --   path = '/usr/lib64/jvm/java-22-openjdk-22',
              --   default = true,
              -- },
            },
          },
        },
      },
    }
  end,
}
```

Currently I can set breakpoint and all that yet pressing f5 leads to 
<img width="1512" alt="Screenshot 2024-04-28 at 18 35 30" src="https://github.com/nvim-java/nvim-java/assets/124557045/a328129b-4030-4c85-b48e-d8e186a4444f">
Which leads to `the selecter configurations refrences 'java', but dap.adapters.java is undefined`.
Any guidance? 🥺
