### ISSUE TITLE
bug: Error executing vim.schedule lua callback: ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: unhandled error ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:55: To enrich the config, projectName should already be present stack traceback

### ISSUE THREAD

**Issue by Mike-18awq** [nvim-java/nvim-java#134]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux

### Describe the bug

Error Message:
Error executing vim.schedule lua callback: ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: unhandled error ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:55: To enrich the config, projectName should already be present
stack traceback:
	[C]: in function 'error'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: in function 'callback'
	...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
	/usr/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

Additional Information:
I followed the steps outlined in the YouTube video titled "[youtube-tutorial](https://www.youtube.com/watch?v=CXv0WUX_E_Q)" for setting up Neovim for Java development.
![1-JavaError](https://github.com/nvim-java/nvim-java/assets/137745753/168b8d28-f063-4564-bcc2-ea22f335d5cf)
![2-JavaError](https://github.com/nvim-java/nvim-java/assets/137745753/1d5a7f15-0383-4ac9-a940-eb254aea1a06)
![3-JavaError](https://github.com/nvim-java/nvim-java/assets/137745753/2b243f47-2d06-4407-b4f6-688c8ec33154)

### Steps To Reproduce

1. I followed the steps outlined in the YouTube video titled "[youtube-tutorial](https://www.youtube.com/watch?v=CXv0WUX_E_Q)"
2. Encounter error during configuration.
3. Receive the aforementioned error message.

### Expected Behavior

Neovim should be configured for Java development without encountering errors.
and...
I am relatively new to using Neovim for Java development. T-T

**Comment by Mike-18awq** [comment]
> ### ¿Revisaste los documentos y los problemas existentes?
> 
>     * [x] He leído todos los documentos del complemento.
> 
>     * [x] He buscado los problemas existentes.
> 
>     * [x] He buscado los problemas existentes de complementos relacionados con este problema.
> 
> 
> ### Versión Neovim (nvim -v)
> 
> 0.9.5
> ### Sistema operativo/versión
> 
> Arco Linux
> ### Describe el error
> 
> Mensaje de error: Error al ejecutar la devolución de llamada de vim.schedule lua: ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: error no controlado ...share/nvim/lazy/nvim- java-dap/lua/java-dap/api/setup.lua:55: Para enriquecer la configuración, el nombre del proyecto ya debería estar presente rastreo de pila: [C]: en función 'error' ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: en la función 'devolución de llamada' ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: en función 'controlador' /usr/share/nvim/runtime/lua/vim/lsp.lua:1393: en función '' vim/_editor.lua: en función <vim/_editor.lua:0>
> 
> Información adicional: Seguí los pasos descritos en el vídeo de YouTube titulado " [ youtube-tutorial ](https://www.youtube.com/watch?v=CXv0WUX_E_Q) " para configurar Neovim para el desarrollo de Java. Incluya cualquier información adicional que pueda ser relevante para solucionar el problema o comprender el problema.
> 
> ![1-Error de Java](https://private-user-images.githubusercontent.com/137745753/312662669-168b8d28-f063-4564-bcc2-ea22f335d5cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA2MjUsIm5iZiI6MTcxMDQzMDMyNSwicGF0aCI6Ii8xMzc3NDU3NTMvMzEyNjYyNjY5LTE2OGI4ZDI4LWYwNjMtNDU2NC1iY2MyLWVhMjJmMzM1ZDVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNTMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNmZhODMyYzMzMzM2ZDc0ODVmNTZmNDU4ZDliODllOGQ5NTJhYjk3Mjc1MDhlZmNmNTk0ZDY1NWU0ZmRhMTk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3BmEyhfBKlNq8hYIwC32ojG94os9D3V4n2OgW18qKjU) ![2-JavaError](https://private-user-images.githubusercontent.com/137745753/312662671-1d5a7f15-0383-4ac9-a940-eb254aea1a06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA2MjUsIm5iZiI6MTcxMDQzMDMyNSwicGF0aCI6Ii8xMzc3NDU3NTMvMzEyNjYyNjcxLTFkNWE3ZjE1LTAzODMtNGFjOS1hOTQwLWViMjU0YWVhMWEwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNTMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDlmYjRmNTQ4NDc3MWVkOWQzMzk3MTUxOTRlNjk2NWUyYTQzMjgwNmZlYzlmM2Q0ZWVkZGZiYjZlNGI0NjhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.gCWMAL2D3ZuBQvmjGqq5WsSmDTq5toNHNIZ6fWQX-Tg) ![3-JavaError](https://private-user-images.githubusercontent.com/137745753/312662673-2b243f47-2d06-4407-b4f6-688c8ec33154.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzA2MjUsIm5iZiI6MTcxMDQzMDMyNSwicGF0aCI6Ii8xMzc3NDU3NTMvMzEyNjYyNjczLTJiMjQzZjQ3LTJkMDYtNDQwNy1iNGY2LTY4OGM4ZWMzMzE1NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxNFQxNTMyMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYmNlNGFjZjYzMTg2MjM2MTEyODcwOGEyODIxMmVmZWZiMzhkNmJkNjEwYTY2ODJhNzRiMDM0NTIzMDM3MGE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SbqtmnJQBrU_VhUx2zfPW4_0QUFWRb6VzXlTMgvobrc)
> ### Steps To Reproduce
> 
>     1. I followed the steps outlined in the YouTube video titled "[youtube-tutorial](https://www.youtube.com/watch?v=CXv0WUX_E_Q)"
> 
>     2. Encounter error during configuration.
> 
>     3. Receive the aforementioned error message.
> 
> 
> ### Expected Behavior
> 
> Neovim should be configured for Java development without encountering errors. and... I am relatively new to using Neovim for Java development. T-T

**Comment by s1n7ax** [comment]
@Mike-18awq Could you update and try again. There is no any function called handler at the moment in the java core. So I'm not quite sure how this was caused. Please re-open is not fixed still.

You can include log files in `~/.local/share/nvim` for more info
