### ISSUE TITLE
Problem with LSP server installation

### ISSUE THREAD

**Issue by jakmaz** [nvim-java/nvim-java#138]
Hello!
I am having troubles with installation of the server on LazyVim. I copied the config to the `~/.config/nvim/lua/plugins/java/init.lua`.
After restarting nvim, the language servers are not being installed like showed in YouTube tutorial.
My servers:
![image](https://github.com/nvim-java/nvim-java/assets/136567999/0f8c33f8-ad70-4f13-b330-281ab094eb79)
Servers from tutorial:
![image](https://github.com/nvim-java/nvim-java/assets/136567999/1c1f6aeb-942e-4bfa-b5a7-fe78edba93ae)

I checked and I don't get errors nor type suggestions in java files.

**Comment by s1n7ax** [comment]
@jakmaz I think I screwed up the plugin trying to fix lombok. Could you try now after updating the plugins.

**Comment by s1n7ax** [comment]
@pravin-dipke Do you have your config pushed to github? By the look of it, you are not passing a table into lsp setup. 

How it is:
```lua
lspconfig.jdtls.setup()
```

How it should be:
```lua
lspconfig.jdtls.setup({})
```

**Comment by pravin-dipke** [comment]
@s1n7ax yes sir i have pushed my config to github here is a link of my commit for nvim-java [https://github.com/pravin-dipke/kickstart.nvim/commit/ef414f510c6f78c0d146e09a7222e8e1bc6f5848](url)

**Comment by pravin-dipke** [comment]
> @pravin-dipke Do you have your config pushed to github? By the look of it, you are not passing a table into lsp setup.
> 
> How it is:
> 
> ```lua
> lspconfig.jdtls.setup()
> ```
> 
> How it should be:
> 
> ```lua
> lspconfig.jdtls.setup({})
> ```

this help now my lspcofig work fine thank you @s1n7ax for help.

**Comment by s1n7ax** [comment]
@jakmaz I assume this is fixed. Please re open if not
