### ISSUE TITLE
bug: Error is thrown when a new jdtls version is installed while an old verision already installed

### ISSUE THREAD

**Issue by s1n7ax** [nvim-java/nvim-java#143]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

-

### Operating system/version

-

### Describe the bug

-

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by s1n7ax** [comment]
Related discussion: https://github.com/orgs/nvim-java/discussions/141

**Comment by bnwa** [comment]
I believe this is the issue I'm encountering as well, I already have `jdtls@1.35.0` installed via Mason as I'm migrating from `nvim-jdtls` however this package has hardcoded `1.31.0`

**Comment by s1n7ax** [comment]
Now jdtls is repackaged with following excluding the timestamp which causes this.
https://github.com/nvim-java/release-jdtls
