### ISSUE TITLE
bug: Missing capabilities on jdtls-1.33.0

### ISSUE THREAD

**Issue by Zeioth** [nvim-java/nvim-java#145]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

arch

### Describe the bug

jdtls-1.33.0 is missing several capabilities
![screenshot_2024-03-21_16-54-32_142771729](https://github.com/nvim-java/nvim-java/assets/3357792/e6d2b1e7-db48-40fd-a0b6-a1c862b9edb0)

jdtls have them
![screenshot_2024-03-21_16-54-02_471118991](https://github.com/nvim-java/nvim-java/assets/3357792/863a8cb4-b6e9-4ca8-8c6f-cd88063d45bb)

The missing LSP capabilities are:
```
"textDocument/codeAction"
"textDocument/codeLens"
"textDocument/hover"
"textDocument/signatureHelp"
"textDocument/references"
"textDocument/rename"
```

A workaround for this issue is to have both jdtls and jdtls-1.33.0 installed, but then you get the nasty notification
![screenshot_2024-03-21_17-03-44_328542822](https://github.com/nvim-java/nvim-java/assets/3357792/ad1d0b7a-9798-4da7-944d-9f9953bf6396)

But it would be ideal to add the missing capabilities to the `jdtls-1.33.0` we are currently shipping.

### Steps To Reproduce

1. Install nvim-java [as specified in the readme](https://github.com/nvim-java/nvim-java?tab=readme-ov-file#hammer-how-to-install).
2. Open a [example project](https://github.com/Zeioth/compiler.nvim/tree/main/tests/examples/languages/java/build).

You won't be able to see references, code lens, or the rest of missing capabilities.

### Expected Behavior

The `jdtls-1.33` we ship from our registers should have the same level of capabilities the `jdtls` shipped by mason has.

**Comment by s1n7ax** [comment]
@Zeioth Thanks for the issue. Turned out when I'm testing I had the `jdtls` package installed. Reverting the change. Please try now. Make sure to remove the any existing `jdtls` packages in mason and let it re-install

**Comment by Zeioth** [comment]
@s1n7ax That fixed the issue indeed thank you. I've tested:

Debugger - OK
![screenshot_2024-03-23_21-57-54_738451337](https://github.com/nvim-java/nvim-java/assets/3357792/c48635b3-7306-41b4-a27b-819bde797715)

Capabilities - OK
![screenshot_2024-03-23_21-58-20_428783417](https://github.com/nvim-java/nvim-java/assets/3357792/7065929a-7fbf-4f2b-ac64-abb617f7f87c)

Installed jdtls version - v1.31.0
![screenshot_2024-03-23_22-03-41_058305920](https://github.com/nvim-java/nvim-java/assets/3357792/f54005c6-981b-4631-b4fc-970eadb6c95c)

The nasty warning show when opening a java project for some reason, but it is not super bad:
![screenshot_2024-03-23_21-59-57_695809448](https://github.com/nvim-java/nvim-java/assets/3357792/5142dc62-ca15-4f84-8d19-c03a299becac)

**Comment by Zeioth** [comment]
The nasty warning show when opening a java project for some reason, but it is not super bad:
![screenshot_2024-03-23_22-12-15_907822561](https://github.com/nvim-java/nvim-java/assets/3357792/b28e5f7c-2b30-40cc-929e-22222c938d21)

**Comment by s1n7ax** [comment]
@Zeioth Can you send the full log when it's failed? It's in `~/.local/state/nvim/lsp.log`

**Comment by Zeioth** [comment]
@s1n7ax yes here I have a clean one: https://pastebin.com/raw/piKVUthZ
