### ISSUE TITLE
bug: dap config not found

### ISSUE THREAD

**Issue by littleghost2016** [nvim-java/nvim-java#152]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2819+gf4df49a95

### Operating system/version

Linux dev 6.6.15-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.6.15-2 (2024-02-04) x86_64 GNU/Linux

### Describe the bug

I want to use lazyVim, graalvm and mvn to write springboot3 project. I have enable dap.core in lazyvim extras. When I run `:JavaRunnerRunMain`, the noise shows `dap config not found`. I run `:JavaDapConfig` to refresh the dap config forcely, the noise shows `DAP configured`. But I run `:JavaRunnerRunMain`, `dap config not found` occurs once again.

### Steps To Reproduce

1. install lazyvim
2. follow the nvim-java installation steps with lazyvim. my config
```lua
return {
  "nvim-java/nvim-java",
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        handlers = {
          ["jdtls"] = function()
            require("java").setup()
          end,
        },
      },
    },
  }
}
```
3. update all plugins
4. enable lazyvim extras dap.core
5. create a new folder, create a empty file named helloworld.java
6. use neovim open the folder. the noice shows `ServiceReady`, `Configuring DAP` and `DAP configured`. I write the code
```java
public class HelloWorld {

    public static void main(String[] args) {

        // Prints "Hello, World" in the terminal window.
        System.out.println("Hello, World");
    }

}
```
7. I run `:JavaRunnerRunMain` and the noice shows `dap config not found`. I run `:JavaDapConfig` and `:JavaRunnerRunMain` but it's no use.
8. the `nvim-java.log` shows
```
[INFO  Sat 06 Apr 2024 11:55:13 PM CST] .../share/nvim/lazy/nvim-java/lua/java/startup/nvim-dep.lua:24: check neovim plugin dependencies
[INFO  Sat 06 Apr 2024 11:55:13 PM CST] ...lazy/nvim-java/lua/java/startup/lspconfig-setup-wrap.lua:11: wrap lspconfig.java.setup function to inject a custom java config
[INFO  Sat 06 Apr 2024 11:55:13 PM CST] ...ev/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:13: add LspAttach event handlers to setup dap adapter & config
[INFO  Sat 06 Apr 2024 11:55:19 PM CST] ...ev/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:48: setup java dap config & adapter
[INFO  Sat 06 Apr 2024 11:55:19 PM CST] ...ev/.local/share/nvim/lazy/nvim-java/lua/java/api/dap.lua:22: configuring dap
[DEBUG Sat 06 Apr 2024 11:55:19 PM CST] ...v/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:82: set dap adapter callback function
[DEBUG Sat 06 Apr 2024 11:55:21 PM CST] ...v/.local/share/nvim/lazy/nvim-java/lua/java/dap/init.lua:93: set dap config:  { {
    mainClass = "HelloWorld",
    name = "nil -> HelloWorld",
    request = "launch",
    type = "java"
  } }
[DEBUG Sat 06 Apr 2024 11:57:37 PM CST] ....local/share/nvim/lazy/nvim-java/lua/java/api/runner.lua:156: dap configs:  { {
    mainClass = "HelloWorld",
    name = "nil -> HelloWorld",
    request = "launch",
    type = "java"
  } }
```
the `nvim-java-core.log` shows
```
[INFO  Sat 06 Apr 2024 11:57:37 PM CST] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:84: creating dap configuration for java
[DEBUG Sat 06 Apr 2024 11:57:37 PM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:32: executing: workspace/executeCommand - vscode.java.resolveMainClass
[DEBUG Sat 06 Apr 2024 11:57:37 PM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:44: vscode.java.resolveMainClass success! response:  { {
    filePath = "/home/dev/gitRepository/testNvim/helloworld.java",
    mainClass = "HelloWorld"
  } }
```
9. when I use lazyvim keymap to run with args, the noice shows
```
   Warn  12:10:53 AM notify.warn Java Configuring DAP
   Info  12:10:54 AM notify.info Java DAP configured
   Warn  12:11:01 AM notify.warn Java Dap config not found
   Error  12:11:14 AM msg_show.lua_error Run with args:  Error executing vim.schedule lua callback: ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: unhandled error ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:55: To enrich the config, projectName should already be present
stack traceback:
	[C]: in function 'error'
	...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:41: in function 'callback'
	...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
	...m/nvim-linux64/share/nvim/runtime/lua/vim/lsp/client.lua:693: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```
so I think that if the problem is the projectName. Thanks for your help!

### Expected Behavior

I could run and debug java file or project.

**Comment by powermaker450** [comment]
same issue

**Comment by s1n7ax** [comment]
Do you have simple project for me to recreate this?

**Comment by atm1020** [comment]
@s1n7ax  I think it's just a simple HelloWorld.java file that has a main class. That's what they trying to run. 
In this situation the jdtls can't return a project name, so this assert is failing: https://github.com/nvim-java/nvim-java-dap/blob/55c90c5d2414f6e66f843f38e111bee284d71e61/lua/java-dap/api/setup.lua#L55 . 


When I deleted the assertion:
  
  1.   `projectName=nil` i got this (with both runner and debug api) :
  
            ```
            .lua:26: 
            failed to run app
            RPC[Error] code_name = UnknownErrorCode, message = "Index 1 out of bounds for length 1" data = {
              message = "Index 1 out of bounds for length 1"
            }
            stack traceback:
                    .../atm1020/workspace/nvim-java/lua/java/handlers/error.lua:18: in function 'error_handler'
                    ...e/nvim/lazy/nvim-java-core/lua/java-core/utils/async.lua:32: in function 'callback'
                    ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:47: in function 'handler'
                    /usr/local/share/nvim/share/nvim/runtime/lua/vim/lsp.lua:1393: in function ''
                    vim/_editor.lua: in function <vim/_editor.lua:0>
            ```
   2.  When projectName = nil, setting it to an empty string resolves the issue . ( The runner API needs a small fix to allow empty project names.)
   
So i think It needs two little fixes in two project (nvim-java, nvim-java-dap) to handle the scenario when jdtls does not return the project name.

@littleghost2016  if you want to setup a Springboot project until it's fixed, you can generate a simple project here: https://start.spring.io/, and it should work fine.

**Comment by s1n7ax** [comment]
For non project classes, it generates a random project name.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/5273e6a7-2b41-4fd5-a410-bdb087ec2e26)

As you can see in the neo-tree, I only got one file other than the git repo.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/3c55a3ed-ce36-4d0f-89f6-58ed2d9eebf0)

**Comment by s1n7ax** [comment]
@littleghost2016 Try making the folder a git repo. You can run `git init` within the folder

**Comment by atm1020** [comment]
> For non project classes, it generates a random project name.
> 
> ![image](https://private-user-images.githubusercontent.com/18459807/322169161-5273e6a7-2b41-4fd5-a410-bdb087ec2e26.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDcxODIsIm5iZiI6MTcxMzAwNjg4MiwicGF0aCI6Ii8xODQ1OTgwNy8zMjIxNjkxNjEtNTI3M2U2YTctMmI0MS00ZmQ1LWE0MTAtYmRiMDg3ZWMyZTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDExMTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkzOTQyMDcwZmYxOTY0NjFjYmJhNzBmZTY1NzU1YzI4NmRkNGY4M2Y0MGU1NzUyOWI1MmJlNjcxN2U3NDAxNjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-lDHZWFehA7tpBBTVnlZ8VRx5t0IEL2FCzkTYaj4nVc)
> 
> As you can see in the neo-tree, I only got one file other than the git repo.
> 
> ![image](https://private-user-images.githubusercontent.com/18459807/322169195-3c55a3ed-ce36-4d0f-89f6-58ed2d9eebf0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDcxODIsIm5iZiI6MTcxMzAwNjg4MiwicGF0aCI6Ii8xODQ1OTgwNy8zMjIxNjkxOTUtM2M1NWEzZWQtY2UzNi00ZDBmLTg5ZjYtNThlZDJkOWVlYmYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDExMTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwNDc0MTlmZWM1ZjNmYjc4NjJhZWI1NGJmOTdlMGE0MGQwMWMzZDVmMzZmM2JjYmZiNDUyOWJmZjJlZWM3MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Bh66WXH5Xcvey6xh8hwlQdIUFyCE4B4mYBxfdAT7iHU)

The .git folder is crucial as a root marker in thease situations, if I understood correctly ?

In the other hand, I noticed that if you init git after the jdtls is already initizilized on the project folder, the project name is still nil (whether you reopen the project or not.), because of the jdtls cache i gues. After cleaning up the `~/.cache/nvim/jdtls/workspaces/common-workspace/` folder, it started working fine as you said.

**Comment by s1n7ax** [comment]
@atm1020 Since there are no any other markers, yes. It's a LSPConfig feature. I only have added bit more markers. That cache is causing many issues. We should have a feature to remove the cache & other stuff like `.classpath` `.project` to force jdtls to rebuild the project

https://github.com/neovim/nvim-lspconfig/blob/6e5c78ebc9936ca74add66bda22c566f951b6ee5/lua/lspconfig/server_configurations/jdtls.lua?plain=1#L79-L89

**Comment by atm1020** [comment]
@s1n7ax  It would be usefull feature!  If you provide me with more details about this idea,  I am ready to work on it.

**Comment by atm1020** [comment]
@s1n7ax I opened a pr (https://github.com/nvim-java/nvim-java-core/pull/62) to handle the situation when the root markers were missing. I think it will solve this issue.

**Comment by littleghost2016** [comment]
Thanks to @s1n7ax @atm1020 for your help!

1. @s1n7ax I create a new folder named `testNvim` and use neovim to open the folder. I create a file named `HelloWorld.java` in neo-tree and open it. Then I write the code.
```java
 public class HelloWorld {

    public static void main(String[] args) {

        // Prints "Hello, World" in the terminal window.
        System.out.println("Hello, World");
    }

}
```
The problem occurs. 

2. After I run `git init`, the problem still exists.'
3. After I remove the folder `/.cache/nvim/jdtls/workspaces/common-workspace/` as @atm1020 said and keep the `.git` folder exists, the code could run without problem.
4. I download the springboot project on https://start.spring.io/ with lombok, jpa, web. I run the project with nvim-java no problem.

**Comment by littleghost2016** [comment]
I've encountered another problem, thanks to the developers for your help.

I could see `Java Configuring DAP` and `Java DAP configured` but `:JavaRunnerRunMain` shows `Java Config not found`.

Here is the reproduce steps.
1. git clone a repository running `git clone https://github.com/dromara/RuoYi-Vue-Plus` and use neovim to open the repository. 
2. after `Java DAP configured`, I run `:JavaRunnerRunMain` and the noice shows `Java Config not found`. I use 'nvim-dap-ui' to run and it shows `DAP No configuration found for java. You need to add configs to dap.configurations.java (See :h dap-configuration)`. The `nvim-java-core.log` shows.
```
[DEBUG Mon 15 Apr 2024 09:20:35 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:23: generating jdtls config
[DEBUG Mon 15 Apr 2024 09:20:35 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:89: generated jdtls setup config:  {
  cmd = { "java", "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dosgi.checkConfiguration=true", "-Dosgi.sharedConfiguration.area=/home/dev/.local/share/nvim/mason/share/jdtls/config", "-Dosgi.sharedConfiguration.area.readOnly=true", "-Dosgi.configuration.cascaded=true", "-Xms1G", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-javaagent:/home/dev/.local/share/nvim/mason/share/lombok-nightly/lombok.jar", "-jar", "/home/dev/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar", "-configuration", "/home/dev/.cache/nvim/jdtls", "-data", "/home/dev/.cache/nvim/jdtls/workspaces/common-workspace" },
  init_options = {                                                                                                                                                                              bundles = { "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-api_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-engine_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-migrationsupport_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-params_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-commons_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-engine_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-launcher_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-runner_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-api_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-commons_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-engine_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-vintage-engine_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.apiguardian.api_1.1.2.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit4.runtime_1.3.0.v20220609-1843.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit5.runtime_1.1.100.v20220907-0450.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.opentest4j_1.2.0.jar", "/home/dev/.local/share/nvim/mason/share/java-test/com.microsoft.java.test.plugin-0.40.1.jar", "/home/dev/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin-0.50.0.jar", "/home/dev/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin.jar",
      <metatable> = <1>{
        __index = <table 1>,
        concat = <function 1>,
        every = <function 2>,
        find = <function 3>,
        flatten = <function 4>,
        for_each = <function 5>,
        includes = <function 6>,
        join = <function 7>,
        map = <function 8>,
        new = <function 9>,
        push = <function 10>
      }
    },
    extendedClientCapabilities = {
      advancedExtractRefactoringSupport = true,
      advancedOrganizeImportsSupport = true,
      classFileContentsSupport = true,
      executeClientCommandSupport = true,
      generateConstructorsPromptSupport = true,
      generateDelegateMethodsPromptSupport = true,
      generateToStringPromptSupport = true,
      hashCodeEqualsPromptSupport = true,
      inferSelectionSupport = { "extractMethod", "extractVariable", "extractConstant", "extractVariableAllOccurrence" },
      moveRefactoringSupport = true,
      overrideMethodsPromptSupport = true
    },
    workspace = "/home/dev/.cache/nvim/jdtls/workspaces/common-workspace"
  },
  root_dir = <function 11>
}
[DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:100: finding the root_dir with root_markers  { "settings.gradle", "settings.gradle.kts", "pom.xml", "build.gradle", "mvnw", "gradlew", "build.gradle", "build.gradle.kts", ".git" }
[DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:105: root of /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin/src/main/java/org/dromara/DromaraApplication.java is /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin
[DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:100: finding the root_dir with root_markers  { "settings.gradle", "settings.gradle.kts", "pom.xml", "build.gradle", "mvnw", "gradlew", "build.gradle", "build.gradle.kts", ".git" }
[DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:105: root of /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin/src/main/java/org/dromara/DromaraApplication.java is /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin
[INFO  Mon 15 Apr 2024 09:20:42 AM CST] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:84: creating dap configuration for java
[DEBUG Mon 15 Apr 2024 09:20:42 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:32: executing: workspace/executeCommand - vscode.java.resolveMainClass
[DEBUG Mon 15 Apr 2024 09:20:49 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:44: vscode.java.resolveMainClass success! response:  {}
[INFO  Mon 15 Apr 2024 09:21:00 AM CST] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:84: creating dap configuration for java
[DEBUG Mon 15 Apr 2024 09:21:00 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:32: executing: workspace/executeCommand - vscode.java.resolveMainClass
[DEBUG Mon 15 Apr 2024 09:21:00 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:44: vscode.java.resolveMainClass success! response:  {}
```
I see the last line said `vscode.java.resolveMainClass` response `{}` so I think if this project lacks `mvnw` file or `.mvn` folder. I copy another project's `mvnw` file and `.mvn` folder to this project and rm `~/.cache/nvim/jdtls/workspaces/common-workspace/` but no helps and I don't know why. When I use vscode remote extension to open the project, it can find the main class and run or debug. Thanks for your help.

**Comment by s1n7ax** [comment]
Going to need sometime to look into this

**Comment by s1n7ax** [comment]
@littleghost2016 Please try again. Now you don't need a git repo. @atm1020 has done a fix for this. You might have to remove jdtls cache first.

**Comment by s1n7ax** [comment]
@littleghost2016 Feel free to reopen if not working

**Comment by atm1020** [comment]
> I've encountered another problem, thanks to the developers for your help.
> 
> I could see `Java Configuring DAP` and `Java DAP configured` but `:JavaRunnerRunMain` shows `Java Config not found`.
> 
> Here is the reproduce steps.
> 
> 1. git clone a repository running `git clone https://github.com/dromara/RuoYi-Vue-Plus` and use neovim to open the repository.
> 2. after `Java DAP configured`, I run `:JavaRunnerRunMain` and the noice shows `Java Config not found`. I use 'nvim-dap-ui' to run and it shows `DAP No configuration found for java. You need to add configs to dap.configurations.java (See :h dap-configuration)`. The `nvim-java-core.log` shows.
> 
> ```
> [DEBUG Mon 15 Apr 2024 09:20:35 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:23: generating jdtls config
> [DEBUG Mon 15 Apr 2024 09:20:35 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:89: generated jdtls setup config:  {
>   cmd = { "java", "-Declipse.application=org.eclipse.jdt.ls.core.id1", "-Dosgi.bundles.defaultStartLevel=4", "-Declipse.product=org.eclipse.jdt.ls.core.product", "-Dosgi.checkConfiguration=true", "-Dosgi.sharedConfiguration.area=/home/dev/.local/share/nvim/mason/share/jdtls/config", "-Dosgi.sharedConfiguration.area.readOnly=true", "-Dosgi.configuration.cascaded=true", "-Xms1G", "--add-modules=ALL-SYSTEM", "--add-opens", "java.base/java.util=ALL-UNNAMED", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-javaagent:/home/dev/.local/share/nvim/mason/share/lombok-nightly/lombok.jar", "-jar", "/home/dev/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar", "-configuration", "/home/dev/.cache/nvim/jdtls", "-data", "/home/dev/.cache/nvim/jdtls/workspaces/common-workspace" },
>   init_options = {                                                                                                                                                                              bundles = { "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-api_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-engine_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-migrationsupport_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-jupiter-params_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-commons_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-engine_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-launcher_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-runner_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-api_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-commons_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-platform-suite-engine_1.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/junit-vintage-engine_5.9.3.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.apiguardian.api_1.1.2.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit4.runtime_1.3.0.v20220609-1843.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.eclipse.jdt.junit5.runtime_1.1.100.v20220907-0450.jar", "/home/dev/.local/share/nvim/mason/share/java-test/org.opentest4j_1.2.0.jar", "/home/dev/.local/share/nvim/mason/share/java-test/com.microsoft.java.test.plugin-0.40.1.jar", "/home/dev/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin-0.50.0.jar", "/home/dev/.local/share/nvim/mason/share/java-debug-adapter/com.microsoft.java.debug.plugin.jar",
>       <metatable> = <1>{
>         __index = <table 1>,
>         concat = <function 1>,
>         every = <function 2>,
>         find = <function 3>,
>         flatten = <function 4>,
>         for_each = <function 5>,
>         includes = <function 6>,
>         join = <function 7>,
>         map = <function 8>,
>         new = <function 9>,
>         push = <function 10>
>       }
>     },
>     extendedClientCapabilities = {
>       advancedExtractRefactoringSupport = true,
>       advancedOrganizeImportsSupport = true,
>       classFileContentsSupport = true,
>       executeClientCommandSupport = true,
>       generateConstructorsPromptSupport = true,
>       generateDelegateMethodsPromptSupport = true,
>       generateToStringPromptSupport = true,
>       hashCodeEqualsPromptSupport = true,
>       inferSelectionSupport = { "extractMethod", "extractVariable", "extractConstant", "extractVariableAllOccurrence" },
>       moveRefactoringSupport = true,
>       overrideMethodsPromptSupport = true
>     },
>     workspace = "/home/dev/.cache/nvim/jdtls/workspaces/common-workspace"
>   },
>   root_dir = <function 11>
> }
> [DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:100: finding the root_dir with root_markers  { "settings.gradle", "settings.gradle.kts", "pom.xml", "build.gradle", "mvnw", "gradlew", "build.gradle", "build.gradle.kts", ".git" }
> [DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:105: root of /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin/src/main/java/org/dromara/DromaraApplication.java is /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin
> [DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:100: finding the root_dir with root_markers  { "settings.gradle", "settings.gradle.kts", "pom.xml", "build.gradle", "mvnw", "gradlew", "build.gradle", "build.gradle.kts", ".git" }
> [DEBUG Mon 15 Apr 2024 09:20:40 AM CST] ...y/nvim-java-core/lua/java-core/ls/servers/jdtls/init.lua:105: root of /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin/src/main/java/org/dromara/DromaraApplication.java is /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin
> [INFO  Mon 15 Apr 2024 09:20:42 AM CST] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:84: creating dap configuration for java
> [DEBUG Mon 15 Apr 2024 09:20:42 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:32: executing: workspace/executeCommand - vscode.java.resolveMainClass
> [DEBUG Mon 15 Apr 2024 09:20:49 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:44: vscode.java.resolveMainClass success! response:  {}
> [INFO  Mon 15 Apr 2024 09:21:00 AM CST] ...share/nvim/lazy/nvim-java-dap/lua/java-dap/api/setup.lua:84: creating dap configuration for java
> [DEBUG Mon 15 Apr 2024 09:21:00 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:32: executing: workspace/executeCommand - vscode.java.resolveMainClass
> [DEBUG Mon 15 Apr 2024 09:21:00 AM CST] ...nvim-java-core/lua/java-core/ls/clients/jdtls-client.lua:44: vscode.java.resolveMainClass success! response:  {}
> ```
> 
> I see the last line said `vscode.java.resolveMainClass` response `{}` so I think if this project lacks `mvnw` file or `.mvn` folder. I copy another project's `mvnw` file and `.mvn` folder to this project and rm `~/.cache/nvim/jdtls/workspaces/common-workspace/` but no helps and I don't know why. When I use vscode remote extension to open the project, it can find the main class and run or debug. Thanks for your help.

@s1n7ax  The fix I created handles the initial problem, but this one is related to multimodule projects. Therefore, I think we should open a new bug for this.

I think the runner/debug API is not working because the command 'vscode.java.resolveMainClass' returned an empty table
 (as you see in the logs). So the main class resolve is not working as expected with this multimodule project.  It's possible that the jdtls only scans the pom file/project under the ` /home/dev/gitRepository/RuoYi-Vue-Plus/ruoyi-admin` folder (this is the project root folder as you see in the logs) , but in this case it's not enough to resolve the infoes like main class project name etc..

When I "forced" jdtls to scan from the project root folder, the 'vscode.java.resolveMainClass' returned all main classes, and the runner/debug API is working fine.

I found two ways to force it:
 1) Set the root directory as project root directory (forced from the nvim-java-core project to always use the fallback directory). 
	Maybe, because of the project like this, the project's root directory can be configurable, similar to profiles.  
 2) Create and open a random Java file in the root folder of the project.
