### ISSUE TITLE
bug: Failure when activating non existing profile

### ISSUE THREAD

**Issue by s1n7ax** [nvim-java/nvim-java#159]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

-

### Operating system/version

-

### Describe the bug

-

### Steps To Reproduce

-

### Expected Behavior

-

**Comment by atm1020** [comment]
@s1n7ax  Could you please provide more information?  I don't understand because, it is not possible to set a profile as active until it has been saved.

**Comment by s1n7ax** [comment]
Issue was when activate is run on vertical line for example, it throws an error. But this is fixed now

![image](https://github.com/nvim-java/nvim-java/assets/18459807/f949344b-6129-40c5-a00e-a708bac7aa1f)
