### ISSUE TITLE
feature: Support of jdtls Java extensions.

### ISSUE THREAD

**Issue by bmihovski** [nvim-java/nvim-java#161]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

We are not able to use the jdtls Java extensions. I tried to use require('java.utils.jdtls') but is not working.

```lua
local jdtls = require('jdtls')

-- Helper function for creating keymaps
function nnoremap(rhs, lhs, bufopts, desc)
  bufopts.desc = desc
  vim.keymap.set("n", rhs, lhs, bufopts)
end


-- The on_attach function is used to set key maps after the language server
-- attaches to the current buffer
local on_attach_jdtls = function(client, bufnr)

  -- Java extensions provided by jdtls
  nnoremap("<C-o>", jdtls.organize_imports, bufopts, "Organize imports")
  nnoremap("<space>ev", jdtls.extract_variable, bufopts, "Extract variable")
  nnoremap("<space>ec", jdtls.extract_constant, bufopts, "Extract constant")
  vim.keymap.set('v', "<space>em", [[<ESC><CMD>lua require('jdtls').extract_method(true)<CR>]],
    { noremap=true, silent=true, buffer=bufnr, desc = "Extract method" })
end
````

### Describe the solution you'd like

It will be great to support the jdtls Java extensions, like "Extract variable",  "Organize imports", "Extract constant" at least like keymaps. If possible we can go further and have them as commands.

### Describe alternatives you've considered

It looks like we can use these features when nvim-jdtls is installed. For more details: https://sookocheff.com/post/vim/neovim-java-ide/

**Comment by s1n7ax** [comment]
@bmihovski `nvim-java` (this plugin) and `nvim-jdtls` are two different plugins for Neovim. In `nvim-jdtls` has refactoring features. Those are not yet implemented in `nvim-java`. If you have plans to use `nvim-java` then you should remove `nvim-jdtls`.

**Comment by s1n7ax** [comment]
You can watch this https://github.com/nvim-java/nvim-java/issues/96 for future updates
