### ISSUE TITLE
mason keeps trying to install an invalid jdtls version

### ISSUE THREAD

**Issue by se-omar** [nvim-java/nvim-java#164]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOS 13.0.1

### Describe the bug

when starting neovim after installing nvim-java, mason opens up and tries to install jdtls version 1.31 from this [link](https://download.eclipse.org/jdtls/milestones/1.31.0/jdt-language-server-1.31.0-202402151717.tar.gz) which is invalid so mason fails.

I forked the repo and changed the jdtls version in lua/java/startup/mason-dep.lua from 1.31.0 to 1.33.0 and mason installs it successfully.
```

function M.get_pkg_list(config)
	local dependecies = {
		{ name = 'jdtls', version = 'v1.33.0' },
		{ name = 'lombok-nightly', version = 'nightly' },
		{ name = 'java-test', version = '0.40.1' },
		{ name = 'java-debug-adapter', version = '0.55.0' },
	}
```

### Steps To Reproduce

1. install nvim-java
2. open neovim
3. mason fails to install jdtls

### Expected Behavior

nvim-java gives mason the latest jdtls version

**Comment by minisiowo** [comment]
Same situation in my case...

**Comment by s1n7ax** [comment]
@se-omar @minisiowo Probably because mason configuration is not done correctly.

https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx

**Comment by krusator** [comment]
@s1n7ax  the linked solution does not fix this issue in my case. Mason still wants to download the invalid version of 1.31.0/jdt-language-server-1.31.0-202404031240.tar.gz.
Correct version should be /jdtls/milestones/1.34.0/jdt-language-server-1.34.0-202404031240.tar.gz

**Comment by s1n7ax** [comment]
@krusator latest version is 1.34.0 but doesn't mean we have to use that. What we are using is the 1.31.0 version. If it's being installed successfully and everything works as expected, don't worry about the version.
