### ISSUE TITLE
bug: Lombok is nog longer detected

### ISSUE THREAD

**Issue by woutervanveen** [nvim-java/nvim-java#165]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4.1

### Describe the bug

I had to reinstall my setup. With a fresh installation of nvim + lazy vim I cannot get nvim-java to work with Lombok again. I tried to look into the code, but I am not sure where the jar is added to the jdtls path. 

### Steps To Reproduce

1. Install nvim-java
2. Try top open code base that uses Lombok

### Expected Behavior

I expect that the Lombok annotations works normally.

**Comment by woutervanveen** [comment]
@s1n7ax thank you for your swift response. The issue started in a repository that is working fine in stuff like IntelliJ and was working well with this plugin. I've setup a repo for which I can reproduce the issue:

https://github.com/woutervanveen/nvim-java-demo

here is also the screenshot of Mason:
<img width="632" alt="Screenshot 2024-04-22 at 19 31 33" src="https://github.com/nvim-java/nvim-java/assets/14922259/c977276d-13a4-4c28-a9b6-73242de20b65">

**Comment by s1n7ax** [comment]
What happened to the other mason dependencies? You should have all of these.

```
◍ java-debug-adapter
◍ java-test
◍ jdtls
◍ lombok-nightly
◍ openjdk-17
```

Working on my end. Could be the cache. Could you try removing following files.

`~/.cache/nvim/jdtls/`, `./.classpath` & `./.project`

![image](https://github.com/nvim-java/nvim-java/assets/18459807/f585f493-c159-4365-bc37-6deaceefa5bd)

**Comment by woutervanveen** [comment]
I also saw this  morning. I removed everything and now it is working fine. I will close the bug. Thank you so much for the help and this wonderful plugin!

**Comment by hrllk** [comment]
hi, i'm facing similar issue .. 
exactly, my project can detect lombok like this 

<img width="568" alt="Screenshot 2024-05-01 at 2 15 37 PM" src="https://github.com/nvim-java/nvim-java/assets/89384517/e08e260b-e823-4887-a73c-7dfd4fcfe091">

but.. i can not invoke getter, setter of a model 

<img width="833" alt="Screenshot 2024-05-01 at 2 16 45 PM" src="https://github.com/nvim-java/nvim-java/assets/89384517/0a4c4a75-996c-4c2a-b9c2-27c1af48472b">

would you let me any advice.. TT??

**Comment by incafox** [comment]
same issue here, I cant work using Lombok. Any help suggestion ?

**Comment by s1n7ax** [comment]
Please create a Java project with minimal dependencies in which i can recreate this.

**Comment by beyondlex** [comment]
I encountered the same issue.

When executing `:LspInfo` in the buffer containing a Java file, I found that the `cmd` for the jdtls client did not include `--javaagent: ...lombok.jar`.

Although Mason installed `lombok-nightly`, it wasn't being utilized.

Upon investigation, I discovered that the current `lspconfig.setup` being used was from `lang.java` in `:LazyExtras`, not from `lspconfig.setup` within `nvim-java` (which is [wrapped in nvim-java-core](https://github.com/nvim-java/nvim-java-core/blob/469aabd3e88cfa3a4d131f81de8b8caed14cb585/lua/java-core/ls/servers/jdtls/init.lua#L38) ).

As a solution, I disabled `lang.java` and added `require("lspconfig").jdtls.setup({})` to the configuration in `~/.config/nvim/lua/plugins/java/init.lua`.


```lua
return {
  "nvim-java/nvim-java",
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-refactor",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        handlers = {
          ["jdtls"] = function()
            require("java").setup()
            require("lspconfig").jdtls.setup({}) -- Add this line for using the wrapped jdtls.setup
          end,
        },
      },
    },
  },
  opts = {},
}
```

After configuring, upon reopening the Java file and executing `:LspInfo`, I can see the `cmd` had been updated, and the lombok is working.

![Xnip2024-06-14_12-01-21](https://github.com/nvim-java/nvim-java/assets/7869143/f66d88c8-72d8-4808-8554-cac06f9d9c0c)

**Comment by Raphael-Soares** [comment]
same issue, doesnt work even with the configs above. Any help suggestions?

**Comment by tranquangdat-w** [comment]
same issue :( Any help suggestions?

**Comment by MohammadAburihan** [comment]
> same issue, doesnt work even with the configs above. Any help suggestions?

Did you find the solution?

**Comment by logrusx** [comment]
> > same issue, doesnt work even with the configs above. Any help suggestions?
> 
> Did you find the solution?

Find the issue for Mason 2.0 migration and look at the comments.

**Comment by tranquangdat-w** [comment]
I change to nvimjdtls, it work very fast than nvim-java. i don't know why

**Comment by logrusx** [comment]
Could you please share your nvim-jdtls configuration?

**Comment by logrusx** [comment]
> I change to nvimjdtls, it work very fast than nvim-java. i don't know why

Because nvim-java pulls spring-boo.nvim which setups Srping Boot language server. Aside from that, after #384 has been resolved, lombok should work fine.

Another reason for lombok not working might be jdtls being setup before nvim-java. Be careful because mason-lspconfig setups all installed LSP's so if you don't take measures to setup nvim-java before that, it can't do its job setting up jdtls properly.

**Comment by logrusx** [comment]
@farazalidev your LspInfo indicates your JDTLS is completely not configured by nvim-java likely due to misconfiguration of nvim-java itself.

It is configured by nvim-lspconfig which does the absolute minimal configuration. I think nvim-java didn't start at all in your case.
