### ISSUE TITLE
bug: Jdtls not using the installed openjdk-17

### ISSUE THREAD

**Issue by lpoto** [nvim-java/nvim-java#167]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2324+g4948fa42e

### Operating system/version

Ubuntu 22.04.3 LTS 

### Describe the bug

Even though the openjdk-17 is successfully installed and the correct JAVA_HOME and PATH are set up in cmd_env,
jdtls still uses a different version (when there is another java version's bin in the $PATH).

The only way I managed to go around this is by replacing "java" with the path to openjdk-17's binary in the jdtls cmd when auto_install = true.

### Steps To Reproduce

1. Have another java binary in the path
2. configure nvim-java with jdk.auto_install = true

### Expected Behavior

Jdtls should use the installed openjdk-17 when auto_install = true

**Comment by s1n7ax** [comment]
@lpoto set `auto_install = false`, then un install openjdk-17 from mason. It should not auto install. You might have to clean and rebuild

https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-how-to-clean-rebuild
