### ISSUE TITLE
bug: After running JavaRunnerRunMain, it works fine. But when I close the opened terminal and try again it doesn't work

### ISSUE THREAD

**Issue by FranciscoAz1** [nvim-java/nvim-java#168]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.0 commit db1b0ee3b30f

### Operating system/version

MacOs 11.5

### Describe the bug

bug: After running JavaRunnerRunMain, it works fine. But when I close the opened terminal and try again it doesn't work. Have tried to run JavaRunnerStopMain. and then JavaRunnerRunMain again and still doesn't work. Also the debugger isn't working to run without args

### Steps To Reproduce

install plugin, in default. And run the command JavaRunnerRunMain in a *.java file, then close the terminal that this command opens. And try to run JavaRunnerRunMain command again

### Expected Behavior

What is supposed to happen is when I rerun the terminal works as the first time before closing the terminal

**Comment by TheFancyOstrich** [comment]
I have the same issue, but on Arch Linux with neovim version 0.9.5. Also the JavaTest commands have the same behaviour.

**Comment by s1n7ax** [comment]
@FranciscoAz1 @TheFancyOstrich I tested this. There is `JavaRunnerToggleLogs` to toggle the logs. Though the log window is NOT be opened automatically, main will be ran successfully.

**Comment by s1n7ax** [comment]
@FranciscoAz1 @TheFancyOstrich Please reopen if that's not the case
