### ISSUE TITLE
bug: jdtls installation fails because it is trying to download a file which does not exist

### ISSUE THREAD

**Issue by doesDeveloper** [nvim-java/nvim-java#181]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Linux ubutnu

### Describe the bug

 Downloading file "https://download.eclipse.org/jdtls/milestones/1.31.0/jdt-language-server-1.31.0-202404031240.tar.gz"…
        spawn: wget failed with exit code 8 and signal 0. 
        Failed to download file "https://download.eclipse.org/jdtls/milestones/1.31.0/jdt-language-server-1.31.0-202404031240.tar.gz".

### Steps To Reproduce

1. setup the plugin
2. wait for it to install dependencies
3. it fails 

### Expected Behavior

Correctly sets up.

**Comment by saidbelkacem** [comment]
Hi, I had the same issue, but it was my mistake. I had jdtls in the list of server, which Mason automatically installs. Maybe this could be your problem too.

**Comment by s1n7ax** [comment]
this could be another reason
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx

**Comment by an1shthomas** [comment]
thanks @s1n7ax I was able to fix the issue by following https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx (method 3)

**Comment by s1n7ax** [comment]
@11D-Beyonder 
https://github.com/nvim-java/nvim-java/issues/181#issuecomment-2102468760

**Comment by s1n7ax** [comment]
It seems right now there is no way to add mason registries programmatically so until then this will verify the nvim-java registry is in the list of registries and throw an error

https://github.com/nvim-java/nvim-java/issues/224
https://github.com/williamboman/mason.nvim/issues/1749
