### ISSUE TITLE
feature: Application to run multiple application at the same time in multi module project

### ISSUE THREAD

**Issue by chetra-seng** [nvim-java/nvim-java#182]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

I'm new to Neovim. I also managed to set it up and run my Spring boot application. I have multiple main classes in my project and I want to run them in different buffers.  However, whenever I tried to run another application in a different buffer, it prompted me to select a class and shut down the previous running application. I went through the documentation multiple time and couldn't find how I can start multiple applications. Am I missing something here?

### Describe the solution you'd like

I would like the ability to run another java application in a different buffers without stopping the previous application

### Describe alternatives you've considered

idk

**Comment by chetra-seng** [comment]
Any updates on this?

**Comment by s1n7ax** [comment]
@chetra-seng Don't have time to look into this. No any progress so far. I would recommend trying overseer.nvim. See if that's any help.

**Comment by chetra-seng** [comment]
Thanks @s1n7ax. I'll give it a try and give u an update. Hopefully things will work out😆😆

**Comment by atm1020** [comment]
@s1n7ax the running API currently does not support this. I think it will be relatively quick to implement, and I am open to handling this.

**Comment by chetra-seng** [comment]
Thanks @atm1020. Can u tell me when the pr can be merged?

**Comment by atm1020** [comment]
@chetra-seng I don't know.

**Comment by s1n7ax** [comment]
@chetra-seng this is merged. You can try it out. @atm1020 Awesome work as always.
