### ISSUE TITLE
feature: Hoping for a Complete Configuration Demo to Set Up and Run Java and Maven Projects

### ISSUE THREAD

**Issue by TomYule** [nvim-java/nvim-java#186]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

Hello, I really want to use your tool for Java development:
https://github.com/nvim-java/nvim-java

I referred to your LazyVim configuration, but I still can't debug, run, or work on Maven projects. I hope you can provide a demo with the complete LazyVim configuration that I can clone and use to run Java and Maven projects.

Here is my configuration:
https://github.com/TomYule/nvim

I don't know where the configuration went wrong. Please help me.

### Describe the solution you'd like

Hello, I really want to use your tool for Java development:
https://github.com/nvim-java/nvim-java

I referred to your LazyVim configuration, but I still can't debug, run, or work on Maven projects. I hope you can provide a demo with the complete LazyVim configuration that I can clone and use to run Java and Maven projects.

Here is my configuration:
https://github.com/TomYule/nvim

I don't know where the configuration went wrong. Please help me.

### Describe alternatives you've considered

Hello, I really want to use your tool for Java development:
https://github.com/nvim-java/nvim-java

I referred to your LazyVim configuration, but I still can't debug, run, or work on Maven projects. I hope you can provide a demo with the complete LazyVim configuration that I can clone and use to run Java and Maven projects.

Here is my configuration:
https://github.com/TomYule/nvim

I don't know where the configuration went wrong. Please help me.

**Comment by s1n7ax** [comment]
@TomYule I have this video where I'm setting up lazyvim from scratch. 
https://youtu.be/CXv0WUX_E_Q

I have my own config but I'm using colemak DH so you will have to remove most of the mappings
https://github.com/s1n7ax/lazyvim-dotnvim

**Comment by TomYule** [comment]
> @TomYule I have this video where I'm setting up lazyvim from scratch. https://youtu.be/CXv0WUX_E_Q
> 
> I have my own config but I'm using colemak DH so you will have to remove most of the mappings https://github.com/s1n7ax/lazyvim-dotnvim

The demo you provided only runs Java tests, not Java in debug mode. It also seems that Maven support is missing, and the project being run is not a Maven project.

**Comment by s1n7ax** [comment]
@TomYule It works on maven. In the video I do debug the main function. I see you have bunch of dap config are there for java. You shouldn't have any dap configurations for java. Adapter and configurations will be set by the plugin. Information you have here is not enough to debug at all. You can get the logs from `~/.local/share/nvim` directory. Check if you can see any errors.

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-lsp-doesnt-work-on-maven-projects
