### ISSUE TITLE
bug: Error after open lazyvim (using nvim-java guide)

### ISSUE THREAD

**Issue by incafox** [nvim-java/nvim-java#190]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

lazyvim

### Operating system/version

macos 14.5

### Describe the bug

Using last version of Lazyvim:
I added the configuration from the following section in order to get it work for java: 

https://github.com/nvim-java/nvim-java/wiki/Lazyvim

Error : after opening Lazyvim: 
<img width="1136" alt="image" src="https://github.com/nvim-java/nvim-java/assets/4401153/b1658b30-7428-497f-b9b5-060cf1baad16">

### Steps To Reproduce

1. use last version of lazyvim
2. follow the guide: https://github.com/nvim-java/nvim-java/wiki/Lazyvim
3. open lazyvim

### Expected Behavior

no alert/error

**Comment by s1n7ax** [comment]
@incafox Seems unrelated to this plugin.

**Comment by incafox** [comment]
@s1n7ax I understand
