### ISSUE TITLE
bug: postfix completion not shown

### ISSUE THREAD

**Issue by dragove** [nvim-java/nvim-java#192]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

Windows 11

### Describe the bug

I've enabled postfix completion option in jdtls like following

```lua
config = function()
	require("java").setup()
	require("lspconfig").jdtls.setup({
		settings = {
			java = {
				completion = {
					postfix = { enabled = true },
				},
			},
		},
	})
end,
```

but When I write code like  `1.var` or `1.sys` not showing any postfix snippets completion.

### Steps To Reproduce

1. setup lspconfig like I described on the "Describe the bug" section
2. open a java file to write code

### Expected Behavior

The postfix completion should be shown like jdtls on vscode.

As a reference, [vscode's java configuration](https://github.com/redhat-developer/vscode-java/blob/master/package.json#L1006)

**Comment by s1n7ax** [comment]
Does this work on vscode? Didn't even know postfix snippets exists in jdtls

**Comment by dragove** [comment]
yes，on vscode, postfix completion works fine. And I can't do this with `nvim-jdtls` either，maybe it is a 'jdtls' problem

**Comment by asaran07** [comment]
Hey @dragove!

Do you have `nvim-cmp` set up? I didn’t have to enable postfix under jdtls, and it still works for me.

<img width="561" alt="Screenshot 2024-05-31 at 5 31 05 PM" src="https://github.com/nvim-java/nvim-java/assets/123274028/1b09bea5-24d5-4638-a19e-34182f98bc63">

I can share my list of completion plugins if you’d like to try using them to see if it works for you. Please let me know!

**Comment by dragove** [comment]
@asaran07  Thank you for letting me know it's working on your end!. I'm currently a user of a Neovim configuration distribution called `LazyVim`.

Unfortunately, I've also attempted to use `AstroNvim` without success.

I'll appreciate if you could share your configuration,  many thanks in advance!

![Screenshot_20240601_151753](https://github.com/nvim-java/nvim-java/assets/24190403/568c7f19-89b4-4fa6-bb3d-4d2e6b0fcebf)

**Comment by asaran07** [comment]
Hello again @dragove,

I apologize for the delayed response. I’ve cleaned up [my configuration](https://github.com/asaran07/LazyM3.nvim/tree/master) and made it available on GitHub. Please feel free to try it out and see if it works for you.

I’m using `kickstart.nvim`, which still uses **Lazy**, so it should be compatible with your setup. While Kickstart includes some extra features that might seem a bit overwhelming, you should be able to extract the key components like `nvim-java`, `nvim-lspconfig`, and the preconfigured `debug configuration`. Ensure you have those in place.

If you have any questions or need further help, please let me know. I’ll do my best to get back to you promptly. Having Java working on Neovim is quite beneficial, so the effort is definitely worth it.

Thank you, and good luck with your setup!

**Comment by dragove** [comment]
Thanks. I looked into your configuration and I notice you haven't call `require('lspconfig').jdtls.setup({})` like it in the documentation https://github.com/nvim-java/nvim-java?tab=readme-ov-file#custom

And I tried to remove this line on my own configuration and things getting working except I encountered the same problem in https://github.com/nvim-java/nvim-java/issues/103

I'll checkout why this happen later

**Comment by s1n7ax** [comment]
@dragove If things like LSP worked before `jdtls.setup()` that might be an indication of `nvim-jdtls`. You shouldn't have that installed.

**Comment by dragove** [comment]
I haven't installed nvim-jdtls, my configuration for java is here 

https://github.com/dragove/dotfiles/blob/1759ba899f3c5b72c5a838c2d16519ddab800728/nvim/.config/nvim/lua/plugins/lang/java.lua

**Comment by s1n7ax** [comment]
@dragove It's probably some capabilities lazyvim passes. So the trick is to let lazyvim do all that. Remove the nvim-java config you have and copy and paste the config here https://github.com/nvim-java/nvim-java/wiki/Lazyvim

![image](https://github.com/nvim-java/nvim-java/assets/18459807/4aa85b31-0d72-486b-9483-9524fed08227)

**Comment by dragove** [comment]
Thanks for your patience. I followed the wiki and now everything works well. Sorry for not noticing the wiki page.
