### ISSUE TITLE
regression:   jdtls doesn't have the capability `"textDocument/codeAction"`

### ISSUE THREAD

**Issue by Zeioth** [nvim-java/nvim-java#194]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

arch linux

### Describe the bug

jdtls doesn't have the lsp capability "textDocument/codeAction" even though it can actually run code actions.

### Steps To Reproduce

The next mapping won't be available because jdtls doesn't have the capability `"textDocument/codeAction"`

```java
if client.supports_method "textDocument/codeAction" then
  lsp_mappings.n["<leader>la"] = {
    function() vim.lsp.buf.code_action() end,
    desc = "LSP code action",
  }
  lsp_mappings.v["<leader>la"] = lsp_mappings.n["<leader>la"]
end
```

But if you remove the line `if client.supports_method "textDocument/codeAction" then` then the mapping will be available.

### Expected Behavior

jdtls should register the capability `"textDocument/codeAction"`.

**Comment by GustavoJCL** [comment]
i have the same problem, code actions doesn't work for me using `actions-preview.nvim `
I have a minimal config for actions-preview and lspconfig:
```
	'aznhe21/actions-preview.nvim',
	lazy = true,
	opts = function(_, opts)
		opts.telescope = {
			sorting_strategy = 'ascending',
			layout_strategy = 'vertical',
			layout_config = {
				width = 0.7,
				height = 0.8,
				prompt_position = 'top',
				preview_cutoff = 20,
				preview_height = function(_, _, max_lines)
					return max_lines - 25
				end,
			},
		}
	end,
```
lspconfig:
```
require('lspconfig').jdtls.setup {
            settings = {
              java = {
                inlayHints = {
                  parameterNames = {
                    enabled = 'all',
                    exclusions = { 'this' },
                  },
                },
              },
            },
          }
```

**Comment by s1n7ax** [comment]
@Zeioth @GustavoJCL Seems to be working fine. Am I missing something? Try running two commands in the video and let me know the results. 

https://github.com/nvim-java/nvim-java/assets/18459807/e5297836-c467-4252-96d8-b4ac6b5f9248

**Comment by s1n7ax** [comment]
@Zeioth @GustavoJCL Seems to be working fine. Am I missing something? Try running two commands in the video and let me know the results. 


https://github.com/nvim-java/nvim-java/assets/18459807/17e04504-eb46-47cb-91b2-94ab87b609cb

**Comment by Zeioth** [comment]
@s1n7ax I've written a minimal file so you can reproduce easily: [MINIMAL_INIT.lua](https://pastebin.com/FpTi5BKE)

## Instructions
1. download the file
2. run `nvim -c ./minimal_init.lua`
3. open any `.java` file with `:e myfile`
4. write `:messages` to see if the capability is available

That way we ensure our config is not the issue.

**Comment by s1n7ax** [comment]
@Zeioth Language server is attached as soon as it's executed. So printing the capability on attach is not right. For some reason jdtls won't complete loading. Stuck at 31% forever.

Even my own config returns false. But after everything is loaded, capability is there and working.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/72b701e4-0443-4ab2-9b84-7750e02007d2)

**Comment by GustavoJCL** [comment]
> @Zeioth @GustavoJCL Seems to be working fine. Am I missing something? Try running two commands in the video and let me know the results.
> 2024-05-30.17-58-45.mp4

i executed the first command `lua=vim.lsp.get_active_clients()[1].supports_method("textDocument/codeAction")` but it get false, but with the second `vim.lsp.buf.code_action()` works fine, but with `actions-preview.nvim` i can't do anything
this is code actions using code_action():
![image](https://github.com/nvim-java/nvim-java/assets/93671143/2224574e-21e6-4547-9a50-96ed219db54a)

**Comment by s1n7ax** [comment]
@GustavoJCL In your case I can't help since standard nvim function is working. If you have multiple LSPs and jdtls is not the first in the array, `vim.lsp.get_active_clients()[1]` might return some other lsp and it might not have the capability.

**Comment by s1n7ax** [comment]
@Zeioth Got it working. Probably network was slow so took more than usual to load.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/218baff8-428d-40b4-8576-3921bbad8fd7)

Following is working.

```lua
local lazypath = vim.fn.stdpath('data') .. '/lazy/lazy.nvim'
if not vim.loop.fs_stat(lazypath) then
  -- bootstrap lazy.nvim
  -- stylua: ignore
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", "--branch=stable", lazypath })
end
vim.opt.rtp:prepend(vim.env.LAZY or lazypath)


-- install plugins
-- ============================================================================
local plugins = {
	"folke/tokyonight.nvim",

	-- nvim-java [java support]
	-- https://github.com/nvim-java/nvim-java
	-- Reliable jdtls support. Must go before mason-lspconfig and lsp-config.
	{
		"nvim-java/nvim-java",
		dependencies = {
			"nvim-java/lua-async-await",
			"nvim-java/nvim-java-refactor",
			"nvim-java/nvim-java-core",
			"nvim-java/nvim-java-test",
			"nvim-java/nvim-java-dap",
			"MunifTanjim/nui.nvim",
			"neovim/nvim-lspconfig",
			"mfussenegger/nvim-dap",
			"williamboman/mason.nvim",
		},
		opts = {
			notifications = {
				dap = false,
			},
			-- NOTE: One of these files must be in your project root directory.
			--       Otherwise the debugger will end in the wrong directory and fail.
			root_markers = {
				"settings.gradle",
				"settings.gradle.kts",
				"pom.xml",
				"build.gradle",
				"mvnw",
				"gradlew",
				"build.gradle",
				"build.gradle.kts",
				".git",
			},
		},
	},

	--  nvim-lspconfig [lsp configs]
	--  https://github.com/neovim/nvim-lspconfig
	--  This plugin provide default configs for the lsp servers available on mason.
	{
		"neovim/nvim-lspconfig",
		event = "BufEnter",
		dependencies = "nvim-java/nvim-java",
	},

	-- mason-lspconfig [auto start lsp]
	-- https://github.com/williamboman/mason-lspconfig.nvim
	-- This plugin auto starts the lsp servers installed by Mason
	-- every time Neovim trigger the event FileType.
	{
		"williamboman/mason-lspconfig.nvim",
		dependencies = { "neovim/nvim-lspconfig" },
		event = "BufEnter",
		opts = {},
	},

	--  mason [lsp package manager]
	--  https://github.com/williamboman/mason.nvim
	--  https://github.com/zeioth/mason-extra-cmds
	{
		"williamboman/mason.nvim",
		dependencies = { "zeioth/mason-extra-cmds", opts = {} },
		cmd = {
			"Mason",
			"MasonInstall",
			"MasonUninstall",
			"MasonUninstallAll",
			"MasonLog",
			"MasonUpdate",
			"MasonUpdateAll", -- this cmd is provided by mason-extra-cmds
		},
		opts = {
			registries = {
				"github:nvim-java/mason-registry",
				"github:mason-org/mason-registry",
			},
			ui = {
				icons = {
					package_installed = "✓",
					package_uninstalled = "✗",
					package_pending = "⟳",
				},
			},
		},
	},
}
require("lazy").setup(plugins)

-- Run aditional code
-- ============================================================================

vim.cmd.colorscheme("tokyonight")


require("java").setup()
require("lspconfig").jdtls.setup({})
```

**Comment by Zeioth** [comment]
That code does something different. What fails is not the fact you can't run code actions (you can always) but the fact it report the capability is not available (even though it is). You can load jdtls the way you want, and still is gonna report the capability is not available.

Same code but as one liner you can copy paste to test.
```lua
:lua print((function() for _, client in ipairs(vim.lsp.get_clients()) do if client.name == "jdtls" then return client.server_capabilities.codeActionProvider and "jdtls client is running and IT DOES HAVE the textDocument/codeAction capability" or "jdtls client is running BUT IT DOESN'T HAVE the textDocument/codeAction capability" end end return "jdtls client is not running" end)())
```

I've tried to load jdtls, wait several seconds, run the code, and still reports the capability is not available (even though it is).

**Comment by GustavoJCL** [comment]
> @GustavoJCL In your case I can't help since standard nvim function is working. If you have multiple LSPs and jdtls is not the first in the array, `vim.lsp.get_active_clients()[1]` might return some other lsp and it might not have the capability.

yes, now changed to [2] because 1 was none-ls running, now I get true result, but the code actions for java works well, just using `vim.lsp.buf.code_action()`, but with `actions-preview.nvim` plugin it didn't work, it display the actions but when i select one of these options the actions doesn't apply
![image](https://github.com/nvim-java/nvim-java/assets/93671143/c5b0a487-9a84-4526-ac6f-a57fa4254046)

**Comment by Zeioth** [comment]
Funny. It's true jdtls is only capable of reporting its capabilities once it's fully loaded. Meaning we can't check the capabilities on `LspAttach`.

That's not the case with any other lsp server I've tested. But well there is nothing we can do. At least we are aware of it now.

**Comment by s1n7ax** [comment]
@Zeioth @GustavoJCL It's funny. I had server capabilities in a markdown I created 5 months ago. That property is there. It's probably has been removed/renamed by jdtls. But I can't help you. I don't see anything related to this in `vscode-java` plugin. Today I updated extra capabilities match what `vscode-java` has

https://github.com/nvim-java/nvim-java-dap/blob/55c90c5d2414f6e66f843f38e111bee284d71e61/doc/server-capabilities.md?plain=1#L4-L6

**Comment by s1n7ax** [comment]
@GustavoJCL You can report this to the plugin author. He might be able to find an alternative there since native action is working.

**Comment by s1n7ax** [comment]
Found this in neovim core. This is how it find code action supported clients

![image](https://github.com/nvim-java/nvim-java/assets/18459807/9e37e7ab-e9b9-4337-92f4-189f032f3d1b)

https://github.com/neovim/neovim/blob/dde2cc65fd2ac89ad88b19df08dc03cf1da50316/runtime/lua/vim/lsp/buf.lua?plain=1#L798-L807
