### ISSUE TITLE
bug: Fail to start the debugger on standalone java programs

### ISSUE THREAD

**Issue by Zeioth** [nvim-java/nvim-java#195]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

arch linux

### Describe the bug

The debugger fail to open in [the next simple code](https://github.com/Zeioth/compiler.nvim/tree/main/tests/examples/languages/java/build-and-run)
![screenshot_2024-05-28_19-50-00_048940370](https://github.com/nvim-java/nvim-java/assets/3357792/879029bd-1924-4587-b487-9b40ca61a012)

But it run correctly on spring projects
![screenshot_2024-05-28_19-52-25_223748952](https://github.com/nvim-java/nvim-java/assets/3357792/37f4b2ea-8ad8-4895-903a-94c16ef07d82)

### Steps To Reproduce

* Down load [the next simple code](https://github.com/Zeioth/compiler.nvim/tree/main/tests/examples/languages/java/build-and-run)
* Paste the next config

```lua
  {
    "nvim-java/nvim-java",
    ft = { "java" },
    dependencies = {
      "nvim-java/lua-async-await",
      'nvim-java/nvim-java-refactor',
      "nvim-java/nvim-java-core",
      "nvim-java/nvim-java-test",
      "nvim-java/nvim-java-dap",
      "MunifTanjim/nui.nvim",
      "neovim/nvim-lspconfig",
      "mfussenegger/nvim-dap",
      "williamboman/mason.nvim",
    },
    opts = {
      notifications = {
        dap = false,
      },
    },
  },
```
* Then run `:DapContinue`

### Expected Behavior

It should be possible to debug normal java applications, not only spring projects.

**Comment by s1n7ax** [comment]
What if you make the current directory a git repo by running `git init`. Is it still the same?

**Comment by Zeioth** [comment]
after `git init` it does it correctly
![screenshot_2024-05-29_10-06-52_466913615](https://github.com/nvim-java/nvim-java/assets/3357792/fa47005b-65f7-42a7-aab0-e13f64506b6d)

**Comment by s1n7ax** [comment]
@Zeioth Any of the parent directories of the project are git repositories? Home directory may be. It supposed to work without any git repository.

**Comment by s1n7ax** [comment]
It's working in my devcontainer playground I just created without any git repos

https://github.com/nvim-java/play-lazyvim

![image](https://github.com/nvim-java/nvim-java/assets/18459807/8201775b-aa0b-4dbb-9548-ad57091240ea)

**Comment by Zeioth** [comment]
Yes that seems to be the problem. The error happen if a parent directory above the project is a git directory.

If I just put my code in `~/myexample/main.java` it runs correctly
![screenshot_2024-05-29_21-15-00_196740753](https://github.com/nvim-java/nvim-java/assets/3357792/efbe5813-b7fa-4884-a3e4-57bb19446678)

I imagine that has no solution with our current detection method, so I will just document it.

**Comment by Zeioth** [comment]
I see now we have the option `root_markers` to customize the way the root directory is detected.
