### ISSUE TITLE
bug: errors when opening a java file

### ISSUE THREAD

**Issue by Zeioth** [nvim-java/nvim-java#196]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

arch linux

### Describe the bug

Opening a java file, always displays the next message
![screenshot_2024-05-28_20-23-15_511262254](https://github.com/nvim-java/nvim-java/assets/3357792/d853a4b6-4a48-4e69-841c-4dcb9e472425)

Apart from that, everything seems to work correctly (debugger, code actions, codelens...)

### Steps To Reproduce

With the next config, open a java file.
```lua
  {
    "nvim-java/nvim-java",
    ft = { "java" },
    dependencies = {
      "nvim-java/lua-async-await",
      'nvim-java/nvim-java-refactor',
      "nvim-java/nvim-java-core",
      "nvim-java/nvim-java-test",
      "nvim-java/nvim-java-dap",
      "MunifTanjim/nui.nvim",
      "neovim/nvim-lspconfig",
      "mfussenegger/nvim-dap",
      "williamboman/mason.nvim",
    },
    opts = {
      notifications = {
        dap = false,
      },
    },
  },
```

### Expected Behavior

The file open and jdtls load without errors.

**Comment by s1n7ax** [comment]
@Zeioth I have disabled the terminating message based on the notification.dap flag. No active session comes from DAP. That occurs because we are terminating the dap sessions to activate the active profile. So it's we cannot suppress that message.

**Comment by Zeioth** [comment]
After 1.5.1 it's been improved thank you
![screenshot_2024-05-29_10-19-12_579240382](https://github.com/nvim-java/nvim-java/assets/3357792/8b37d313-aaca-4098-bd51-250857884e7e)
