### ISSUE TITLE
bug: textDocument/hover is not supported

### ISSUE THREAD

**Issue by lpoto** [nvim-java/nvim-java#212]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.5

### Describe the bug

Setting up the nvim-java plugin before the jdtls, causes the following exception when calling `vim.lsp.buf.hover()`
```
method textDocument/hover is not supported by any of the servers registered for the current buffer
```

This error is only shown when nvim-java is configured. If I configure just jdtls, it works like expected.

### Steps To Reproduce

1. Use java 21
2. Configure nvim-java `require"java".setup { jdk = { auto_install = false }}`
3. Configure jdtls `require"lspconfig".jdtls.setup{<options>}`

### Expected Behavior

The hover functionality should work regardless of nvim-java being configured.

**Comment by diegoadborges** [comment]
i'm also having the same problem

**Comment by s1n7ax** [comment]
@diegoadborges @lpoto Any of you got the config on github?

**Comment by diegoadborges** [comment]
The config that i'm using is this

```lua
return {
  "nvim-java/nvim-java",
  lazy = false,
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-refactor",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
  },
}
```

**Comment by s1n7ax** [comment]
@diegoadborges Not enough information without the entire config but, try the new installation instructions.

https://github.com/nvim-java/nvim-java?tab=readme-ov-file#hammer-how-to-install

**Comment by diegoadborges** [comment]
I've tried to follow the install guide, but still didn't work

here it's my neovim config https://github.com/diegoadborges/vim-config

**Comment by s1n7ax** [comment]
@diegoadborges It's not reproducible. I get like 100 errors. But nvim-java works fine with following config.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/a55cc331-4c3f-4d62-8761-e6211f03b61b)

![image](https://github.com/nvim-java/nvim-java/assets/18459807/73dbaf09-a714-4323-a483-71f887b0283b)

**Comment by lpoto** [comment]
@diegoadborges 
On my side, the init_options in ` lua/java-core/ls/servers/jdtls/config.lua` seems to be causing an issue.

If I remove the option (or set it to false)

` init_options.extendedClientCapabilities.clientHoverProvider = true`
 
 
 The hover capability starts working again.

**Comment by adelarsq** [comment]
@lpoto Solved for me.

@s1n7ax It occurs both with cmp and native autocompletions. I think that will be necessary some fix here. I will try to take a look on this if I have time.

**Comment by s1n7ax** [comment]
@lpoto How is it related to autocompletion? As far as I can see, it's some capabilities you guys are passing. It's not related to this project.

**Comment by s1n7ax** [comment]
@diegoadborges If you can use this devcontainer and make your configuration reproducible, I could look into it.

https://github.com/nvim-java/play-lazyvim

I literally created a new container with your config and with all the defaults everything works perfectly. I'm using all the default capabilities of vscode java plugin and it seems to work for most people. It's hard to help you when I can't recreate the issue.

**Comment by adelarsq** [comment]
@s1n7ax Yes. Pretty strange that isn't working. I trying to figure out myself, since notice this bug a week ago.

Right now I did use the @lpoto solution together with this function to get the capabilities:

```lua
local function customCapabilities()
    local c = vim.lsp.protocol.make_client_capabilities()
    c.textDocument.foldingRange = {
        dynamicRegistration = false,
        lineFoldingOnly = true
    }
    return c;
end
```
I am using native LSP autocompletion right now, but I did confirm earlier that with cmp plugin also fails.

**Comment by s1n7ax** [comment]
@adelarsq I still have no clue what you are talking about. This issues is related to showing the documentation under the cursor. The function is `vim.lsp.buf.hover()`. How is this related to native auto-completion or nvim-cmp?

**Comment by adelarsq** [comment]
@s1n7ax Yes, exactly that. Forget, just saying what I am using so that can be on any help. But it's not the case.

I did take a look on the LSP implementation:

https://github.com/eclipse-jdtls/eclipse.jdt.ls/blob/b363a8617022e3d7d60b64b6669c823fdda1e1f9/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/preferences/ClientPreferences.java#L270C17-L270C48

I think that for some reason extendedClientCapabilities is not being initiated.

**Comment by lpoto** [comment]
I didn't have time to investigate the root cause of the issue, but I did create a plain configuration with only the plugin set up as outlined in the README. The hover functionality did not work unless I modified the option mentioned earlier.

I also forgot to mention that I've been using this plugin for some time, and this issue only started recently for me.

I appreciate anyone tackling this issue, although I'm content with just tweaking the extendedCapabilities in my config for now.

**Comment by adelarsq** [comment]
@lpoto I'm trying to figure out what it's wrong. I have some suspection that it's some misbehaviour between LSP initialization and DAP (see https://github.com/nvim-java/nvim-java/issues/152). For now I am using your solution.

**Comment by skriems** [comment]
I have the same issue. Literally followed the steps showed in the video to
1. setup a fresh LazyVim installation
2. added the following to `lua/plugins/nvim-java.lua`
```
return {
  "nvim-java/nvim-java",
  config = false,
  dependencies = {
    {
      "neovim/nvim-lspconfig",
      opts = {
        servers = {
          jdtls = {
            -- Your custom jdtls settings goes here
          },
        },
        setup = {
          jdtls = function()
            require("java").setup({
              -- jdk = {
              --   -- install jdk using mason.nvim
              --   auto_install = false,
              -- },
              -- Your custom nvim-java configuration goes here
            })
          end,
        },
      },
    },
  },
}
```

And also get the error about hover being not available 🤷

**Comment by s1n7ax** [comment]
No idea what the hell is going on but I changed the capability to false. With the new update, this should work without passing any custom jdtls config
