### ISSUE TITLE
feature: add JavaRunnerRestartMain command

### ISSUE THREAD

**Issue by wr9dg17** [nvim-java/nvim-java#239]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

It is not really a problem but running `JavaRunnerRestartMain` would be faster than running `JavaRunnerStopMain` and `JavaRunnerStartMain` commands

### Describe the solution you'd like

It would be great to have command to restart running application after making some changes in application code, for example `JavaRunnerRestartMain`

### Describe alternatives you've considered

Nope, vim/neovim forever

**Comment by atm1020** [comment]
@wr9dg17  You can restart the app with the `JavaRunnerStartMain` command (If the app is already running, it will stop the app and start it again).
