### ISSUE TITLE
bug: Client quits while using tmux + neovim

### ISSUE THREAD

**Issue by guglielmobartelloni** [nvim-java/nvim-java#255]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

MacOS 14.4

### Describe the bug

When I open a java project using in tmux with neovim the lsp crashes saying "Client 2 quit with exit code 1 and signal 0". Instead, when I open the same project with only neovim without using tmux everything works as expected. I don't know how to proceed debugging this issue.

### Steps To Reproduce

Load a project in neovim using tmux

### Expected Behavior

Everything should work as expected

**Comment by chetra-seng** [comment]
May I ask if you have jdtls installed? I had the same issue because I had jdtls installed.

**Comment by s1n7ax** [comment]
@guglielmobartelloni Just tried and it works file. Do you have any scripts in tmux configuration that changes the PATH or something? You can check the LSP logs at `~/.local/state/nvim/lsp.log`

**Comment by guglielmobartelloni** [comment]
Hi, sorry for the delayed response. After reconfiguring my zshrc, removing some plugins, and switching to a different package manager, the issue has been resolved. Although I'm not entirely sure of the exact cause, it appears to have been an interaction between zsh and tmux that was disrupting the PATH.
