### ISSUE TITLE
Module not found: java-core.utils.notify

### ISSUE THREAD

**Issue by 50-Course** [nvim-java/nvim-java#258]
nvim-java throws an error at startup stating a missing module is unable to let nvim-java startup.

## Steps to reproduce

- Bare bones cofiguration
- Add `nvim-java` to dependencies
- Uninstall previous installation of `nvim-jdtls` and install `nvim-java` bundle
- Run `PackerSync`

## Environment Setup

- Ubuntu 22.04
- Neovim 0.10 nightly with `packer` as package manager

**Comment by s1n7ax** [comment]
Duplicate https://github.com/nvim-java/nvim-java/issues/249
