### ISSUE TITLE
bug: JavaTestRunCurrentMethod command does not show stdout window

### ISSUE THREAD

**Issue by dca-b** [nvim-java/nvim-java#275]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu 24.04

### Describe the bug

:JavaTestRunCurrentMethod does not the show stdout window anymore.

### Steps To Reproduce

:JavaTestRunCurrentMethod on a test method.

### Expected Behavior

Show a stdout window and results.

**Comment by s1n7ax** [comment]
Don't think we ever had that feature. We have the log in `JavaRunnerRunMain` not for testing. But planning to somehow get all logs into one thing. Not yet decided how

**Comment by s1n7ax** [comment]
@dca-b For results use `JavaTestViewLastReport`

**Comment by dca-b** [comment]
On a test method, I want to show System.out.println. How so?
