### ISSUE TITLE
bug: Error when performing a line break

### ISSUE THREAD

**Issue by Esteban528** [nvim-java/nvim-java#277]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

NixOS 24.11.20240712.7e7c39e (Vicuna) x86_64 

### Describe the bug

Hello, I have this error when skipping line in java, I get this error, I don't know if it's some nvim-java, lsp or lazyVim problem, I have a fresh installation of LazyVim and the only thing I've put has been the nvim-java plugin, I've tried changing jdk and the error is not solved.

The error occurs when I write in this class, in the others it does not always happen

### Steps To Reproduce

1

https://github.com/user-attachments/assets/3bc7223f-1f86-4214-a4a6-4eccbe01fcd4

### Expected Behavior

I was hoping that no annoying mistakes would happen

**Comment by s1n7ax** [comment]
With `vim.lsp.protocol.make_client_capabilities()` inlay hint works fine. I'm also using LazyVim. I get no issue. Seems unrelated to nvim-java too

**Comment by Esteban528** [comment]
How strange, is it because of my distribution?

**Comment by s1n7ax** [comment]
Don't think so. I'm also using Lazyvim as my personal configuration

**Comment by Esteban528** [comment]
I fixed this error by disabling the inlay hint

**Comment by bnwa** [comment]
Am also getting this error with Neovim 0.10, not using a distribution.

**Comment by ArianGohari** [comment]
Hey, I'm getting the same error with Neovim 0.10.0 and also after updating to 0.10.1. And I am getting it only with Java files. I am using a fresh copy of nvim-java/starter-lazyvim. Are there any updates on this issue?

**Comment by superuserd** [comment]
Hi,
seems to be buggy for me too. 

**Describe the bug**
When I use jdk-17 -> getting same error message.
When I use jdk-11 -> no error.

**Comment by aeropagz** [comment]
I also experience this bug on 0.10.2
