### ISSUE TITLE
bug: spring-boot project not showing methods in lsp_document_symbols but will show annotations

### ISSUE THREAD

**Issue by zachcuy** [nvim-java/nvim-java#281]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 24

### Describe the bug

When I access the lsp_document_symbols, it only shows the annotations from Spring. It does not show the methods.

For example, if I have a function as:
```
@Transactional(readOnly = true)
public List<Book> findAll() {
    return bookRepository.findAll();
}
```

The only symbol I would get is `@Transactional(readOnly = true)`. If my method doesn't have an annotation, it won't show up either.

### Steps To Reproduce

1. Install nvim-java and keep everything as default.
2. Open my spring project and a java file in it.
3. Wait for LSP to finish loading.
4. Access lsp_document_symbols.

### Expected Behavior

I would expect it to show my methods as well.

**Comment by s1n7ax** [comment]
By default yes. But you can use something like fzf-lua to find symbol. https://github.com/nvim-java/nvim-java/wiki/Tips-&-Tricks#workspace-symbols-search

![image](https://github.com/user-attachments/assets/94b89f80-a907-4764-ae2d-f335a93b5681)

![image](https://github.com/user-attachments/assets/24a20653-fc8e-4186-a7b2-5777dff48f12)

**Comment by drewma2k** [comment]
This still appears to be an issue. I was able to reproduce it using the LazyVim starter configuration listed in the README
