### ISSUE TITLE
bug: JavaBuildWorkspace no longer works

### ISSUE THREAD

**Issue by chetra-seng** [nvim-java/nvim-java#282]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Windows 11 WSL

### Describe the bug

I've used JavaBuildWorkspace all the time and it's always worked. With latest 2 updates, this command completely broke and I always get this error message when running the command. `E492: Not an editor command: JavaBuildWorkspac`

### Steps To Reproduce

1. Have a multimodule Spring Boot project using Maven
2. Start the command

### Expected Behavior

It should build the whole workspace as the previous version did

**Comment by chetra-seng** [comment]
I have the latest plugin installed
![image](https://github.com/user-attachments/assets/cbb290b5-2ef8-4db7-b069-d0f5ef7ea9e5)

**Comment by s1n7ax** [comment]
@chetra-seng Your config in github? nvim-java is also upto date right?

**Comment by chetra-seng** [comment]
This is my config for java and I've done it based on the page in [Wiki](https://github.com/nvim-java/nvim-java/wiki/Lazyvim#install-nvim-java-on-lazyvim) And yes, everything is up to date

```lua
return {
  "nvim-java/nvim-java",
  config = false,
  dependencies = {
    {
      "neovim/nvim-lspconfig",
      opts = {
        servers = {
          jdtls = {
            -- Your custom jdtls settings goes here
            handlers = {
              -- By assigning an empty function, you can remove the notifications
              -- printed to the cmd
              ["$/progress"] = function(_, result, ctx) end,
            },
          },
        },
        setup = {
          jdtls = function()
            require("java").setup({
              -- Your custom nvim-java configuration goes here
            })
          end,
        },
      },
    },
  },
  keys = {
    {
      "<leader>jb",
      "<cmd>JavaBuildWorkspace<cr>",
      desc = "Build java workspace",
    },
  },
}
```

**Comment by s1n7ax** [comment]
Tried this in a test container. I can't recreate this

**Comment by s1n7ax** [comment]
@chetra-seng Oh wait. I did not realize I have changed the name. Now the command name is `JavaBuildBuildWorkspace`. Additionally you now get `JavaBuildCleanWorkspace` but you have to close and reopen the editor to restart the server.

**Comment by chetra-seng** [comment]
Thanks for the clarification and updating the doc as well.
