### ISSUE TITLE
bug: can't make the plugin work with a basic gradle project

### ISSUE THREAD

**Issue by FabrizioPerria** [nvim-java/nvim-java#299]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS sonoma

### Describe the bug

I can't make this work with a basic gradle project. I created the project running gradle init, then when i went to open the file in neovim i get the following 
<img width="1045" alt="image" src="https://github.com/user-attachments/assets/de0b35d2-3b27-4ada-9ffa-1101dea10929">

here's my lua config
```
return {
    {
        "nvim-java/nvim-java",
        config = false,
        dependencies = {
            "neovim/nvim-lspconfig",
            'nvim-java/lua-async-await',
            'nvim-java/nvim-java-core',
            'nvim-java/nvim-java-test',
            'nvim-java/nvim-java-dap',
            'MunifTanjim/nui.nvim',
        },
    },

    {
        "VonHeikemen/lsp-zero.nvim",
        ...
        config = function()
            ...
            require("mason").setup({})
            require('java').setup({
                root_markers = {
                    "settings.gradle",
                    "settings.gradle.kts",
                    "pom.xml",
                    "build.gradle",
                    "mvnw",
                    "gradlew",
                    "build.gradle",
                    "build.gradle.kts",
                },
            })
            require("mason-lspconfig").setup({
                handlers = {
                    lsp_zero.default_setup,
                },
            })
            require('lspconfig').lua_ls.setup({
                ...
            })
            require('lspconfig').jdtls.setup({
                # I already tried without this section, same result
                settings = {
                    java = {
                        configuration = {
                            runtimes = {
                                {
                                    name = "JavaSE-21",
                                    path = "/opt/homebrew/opt/openjdk@21",
                                    default = true,
                                }
                            }
                        }
                    }
                }

            })
            require('lspconfig').gopls.setup({
                ...
            })
        end,
    },
    ...
}

```
Surely something is misconfigured on my end, but can't figure it out :) the project itself can run via gradlew run.

### Steps To Reproduce

1. mkdir test
2. cd test
3. gradle init and create an application
4. nvim app/src/main/ava/org/example/App.java

### Expected Behavior

lsp ready to go, no errors, able to build the project and enter debugger.

**Comment by Emptyfruit** [comment]
Basic gradle project doesn't work for me either, but the error is different: 

```
RPC[Error] code_name = MethodNotFound, message = "No delegateCommandHandler for vscode.java.resolveMainClass"
```

**Comment by s1n7ax** [comment]
Looks like your mason configuration is not compatible with the expected. Those `String cannot be resolved to a type` errors are usually when the JDKs you have in the configuration does not match any required by the gradle project. For instance, if the gradle project require JDK 23 but in the configuration, you only have 21.

https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx

You can reopen if this is not fixed.
