### ISSUE TITLE
How can we jump to class in jars 

### ISSUE THREAD

**Issue by zeekling** [nvim-java/nvim-java#301]
How can we jump to class in jars

**Comment by andrewnguyen41** [comment]
+1

**Comment by s1n7ax** [comment]
Try this:
https://github.com/nvim-java/nvim-java/wiki/Tips-&-Tricks#workspace-symbols-search

**Comment by s1n7ax** [comment]
Highly recommend using FzfLua over telescope. Faced some errors with telescope

**Comment by PiotrRaszkowski** [comment]
I understand the the question was to jump to jars dependencies? There is this plugin you may try: JavaHello/java-deps.nvim"

```
vim.api.nvim_create_autocmd("LspAttach", {
                    callback = function(args)
 local client = vim.lsp.get_client_by_id(args.data.client_id)
if client and client.name == "jdtls" then
  require("java-deps").attach(client, args.buf)
     vim.api.nvim_buf_create_user_command(args.buf, "JavaProjects",
                    require("java-deps").toggle_outline, {
                          nargs = 0,
                          })
                       end
                 end,
              })

```

**Comment by s1n7ax** [comment]
Confirms that the provided solution works to search any class in any of the dependencies through live symbol search. Telescope doesn't work for some reason but you can use Fzf-lua

https://github.com/nvim-java/nvim-java/wiki/Tips-&-Tricks#workspace-symbols-search

![screenshot 24-10-22 07:51:47](https://github.com/user-attachments/assets/974b2563-00a0-4b0f-a799-8365e2013dbc)
