### ISSUE TITLE
bug: install of jdtls fails (reportedly the target file is not found) 

### ISSUE THREAD

**Issue by manumoreno** [nvim-java/nvim-java#304]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Linux (Arch 6.10.10-arch1-1)

### Describe the bug

Installing the current version of nvim-java fails. jdtls cannot be installed because the target file is missing from Eclipse's website. See attached screenshots...

![screenshot_23092024_013257](https://github.com/user-attachments/assets/b696b47b-00c5-4c47-b3e5-d8dac732191f)
![screenshot_23092024_013237](https://github.com/user-attachments/assets/697b491b-774a-4c79-a932-c67ee4146201)

### Steps To Reproduce

1. Attempt to install the nvim-java plugin using the instructions provided by the developer.
2. On failure one can see that the jdtls LSP fails to install properly. The log information indicates the root cause.

### Expected Behavior

All components provided by nvim-java should install fine.

**Comment by laggedskapari** [comment]
@Hilamiks Oh my god! You are an Angel...Just when I was about to give up. You edited....It got fixed for me too. 
Thank You sooooooooooooo much!

**Comment by BasLangenberg** [comment]
@Hilamiks I must be crazy, but I can't seem to fix this in my config and I have the same issue. If I install manually from Mason it install 1.38, but with my current config it tries to pull 1.37. It seems to come from the mason registry shipped with this plugin for some reason.

How exactly did you override this? I must overlook something obvious but I spent some time on this already and cannot seem to fix it.

**Comment by Hilamiks** [comment]
@BasLangenberg exactly what I did:
1) go to Mason config
2) change this:
config = function()
    require("mason").setup({
        ....//your opts here
    })
end

to this:
opts = {
    ....//your opts here
}

*sorry about formatting I'm on my phone
hope it helps!

**Comment by BasLangenberg** [comment]
Alright, I was searching in the completely wrong direction. I fixed my mason config (which was nothing more than require("mason").setup({}) in a config var, so I removed that) and now the plugin is pulling the correct version of jdtls.

Thanks for your quick reply!
