### ISSUE TITLE
bug: Getting "client not found: spring-boot" on popup and no suggestions found in applications.properties

### ISSUE THREAD

**Issue by mkdirJava** [nvim-java/nvim-java#306]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.39.3

### Operating system/version

Windows WLS2 Ubuntu 

### Describe the bug

Upon initial use, the application.properties suggestion was working
however after swithcing Java versions it seems to have borked upon 
running
JavaBuildCleanWorkspace

### Steps To Reproduce

I am really unsure 

### Expected Behavior

Application.properties suggestion working

**Comment by s1n7ax** [comment]
Unable to recreate
