### ISSUE TITLE
bug: Mason fails to get latest registry

### ISSUE THREAD

**Issue by manumoreno** [nvim-java/nvim-java#309]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1 Build type: RelWithDebInfo

### Operating system/version

Linux Arch 6.11.1-arch1-1

### Describe the bug

Mason is reporting some registry issues. Please see attached screen capture for more details.  I'm also getting the vscode delegation error. I'm not sure if they are related. Thanks man! I appreciate all the work you're doing.

### Steps To Reproduce

Run a Mason update. The error message is reported at the top.

### Expected Behavior

![screenshot_02102024_212813](https://github.com/user-attachments/assets/c18b0f79-5408-46d5-af6a-98e6af133cbc)

**Comment by s1n7ax** [comment]
I just recreated the entire environment from scratch. Everything being installed perfectly.
https://github.com/nvim-java/play-lazyvim

Try removing the directory at this location

```vim
:= vim.fn.stdpath('data') .. '/mason'
```
