### ISSUE TITLE
bug: junit 5 @ParameterizedTest not working properly

### ISSUE THREAD

**Issue by ARManakhov** [nvim-java/nvim-java#310]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Arch Linux x86_64

### Describe the bug

with `mvn test -D.test=FileArgumentProviderTest` one of the parameterized test is failing (as expected)
```
...
[INFO] Running dev.sirosh.case_folders.FolderStringArgumentsProviderTest
[INFO] Tests run: 13, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.093 s -- in dev.sirosh.case_folders.FolderStringArgumentsProviderTest
[INFO] Running dev.sirosh.case_folders.JsonArgumentConverterTest
[INFO] Tests run: 29, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.280 s -- in dev.sirosh.case_folders.JsonArgumentConverterTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   FileArgumentProviderTest.provideArguments:43 
expected: /home/sirosh/Documents/prog/java_projects/case-folders/target/test-classes/test_cat_and_dog/meme/cat
 but was: /home/sirosh/Documents/prog/java_projects/case-folders/target/test-classes/test_cat_and_dog/mine/cat
[INFO] 
[ERROR] Tests run: 45, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
...
```

but when trying to use `:JavaTestRunCurrentClass` 
getting output like this without any error:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended

[Process exited 0]
```

### Steps To Reproduce

1. install nvim, LazyVim, nvim-java
2. clone https://github.com/ARManakhov/case-folders/tree/917a66a9e32fec8396b77e0a766e25a5603708e1
3. run `:JavaTestRunCurrentClass`  for src/test/java/dev/sirosh/case_folders/FileArgumentProviderTest.java

### Expected Behavior

report that one of tests is failed

**Comment by PiotrRaszkowski** [comment]
I have the same issue with JUnit 5 tests but not parametrized, no info about tests, only in the last report:
![image](https://github.com/user-attachments/assets/ff1a5dfb-c0e5-4ba2-9acb-d2f5e451c178)
![image](https://github.com/user-attachments/assets/a5d5cde6-29ec-436b-8fe2-639cb58811aa)

**Comment by PiotrRaszkowski** [comment]
Also I can see that the icons in the report are very small... any hint how to fix it?

**Comment by s1n7ax** [comment]
Try ./gradlew build before opening the project. I don't know the reason why tests are not identified as test when opening a new project. I just tested with @ParameterizedTest and works fine after a build with simple source `    @ValueSource(strings = { "user1", "user2" })`

https://github.com/nvim-java/nvim-java/issues/336

**Comment by pra-va** [comment]
Can confirm. Using Java 21, Gradle, Junit 5 (project created with Spring Initializr.

I have tested out two cenarios:

### 1) The test bellow fails as expected:
```
package org.parameterizedtest.helloworld;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.assertj.core.api.Assertions.assertThat;

class HelloWorldTest {
   @ParameterizedTest()
   @CsvSource(delimiter = '|', value = """
       world | hi
   """)
   void parameterizedTest(String value, String expectedValue) {
       assertThat(value).isEqualTo(expectedValue);
   } 
}
```

### 2) This test fails with `./gradlew build` (as expected), yet, when using JavaTestRunCurrentClass, it passes.
```
package org.parameterizedtest.helloworld;

import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.assertj.core.api.Assertions.assertThat;

class HelloWorldTest {
   @ParameterizedTest()
   @CsvSource(delimiter = '|', value = """
       hello  | hello
       world | hi
   """)
   void parameterizedTest(String value, String expectedValue) {
       assertThat(value).equals(expectedValue);
   } 
}
```

I have default config with dap.core installed and lazyvim; nothing more.

P.S. Amazing job you are doing with nvim-java!!!! I revisit your project from time to time and I feel that very soon I will be able to say goodbye to IntelliJ IDEA 👍🏻
