### ISSUE TITLE
bug: jdtls causing a mason error as the version 1.37.0 isnt available in mason

### ISSUE THREAD

**Issue by BKR-dev** [nvim-java/nvim-java#314]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

nvim v0.10.2

### Operating system/version

macOS 14.7

### Describe the bug

mason is trying to install v1.37.0 but mason doesnt know v1.37.0 but v1.38.0 and can be installed

### Steps To Reproduce

1. install the plugin via the guide
2. open neovim
3. see that mason is failing to install 1.37.0  as it is not avilable
![Screenshot 2024-10-10 at 11 32 26](https://github.com/user-attachments/assets/10b449b3-1223-440b-9ed7-bdad50efb07a)

### Expected Behavior

mason should install jdtls.

i investigated and found that even after installing 1.38.0 mason still tries to install 1.37.0 EVEN THO the mason registry doesnt even know v1.37.0, so it turns out that this version (1.37.0) is pinned in the file that tells mason to install which version of jdtls.

**Comment by BKR-dev** [comment]
i fixed this issue in https://github.com/nvim-java/nvim-java/pull/313

**Comment by PiotrRaszkowski** [comment]
any workaround?

**Comment by BKR-dev** [comment]
Yes update to 1.38.0

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx

**Comment by BKR-dev** [comment]
this doesn't apply if you don't use lazy vim. If you cross reference the mason registry you will see that the mason registry doesn't not contain v1.37.0 anymore and hasn't for at least two months.

**Comment by s1n7ax** [comment]
@BKR-dev So everyone should upgrade because you don't use lazy vim?

**Comment by BKR-dev** [comment]
@s1n7ax no the referenced version should be updated so nobody HAS to use lazy if they dont (want to). as of now you HAVE to use lazy or something similar to solve a simple version problem that i have detailed more than enough. 

again in https://github.com/nvim-java/nvim-java/pull/313 i only matched the version of the mason dependency of nvim-java to the version that mason actually has in its registry. 

please merge and in the future consider to implement an autoimatic update to keep the version up to date to what mason has.

**Comment by s1n7ax** [comment]
> in the future consider to implement an autoimatic update

Fork it and start working on it. Here I do what I think is the best method.

> as of now you HAVE to use lazy or something similar to solve a simple version problem that i have detailed more than enough

If you are not using lazy, mention that first in the issue. In the steps to reproduce you said

> install the plugin via the guide

This is literally the most asked question in this project. I have explained this enough. This has nothing to do with the package manager. You need to have custom mason registry from nvim-java when setting up Mason.nvim. It's clearly defined in the `lazy.lua`. That's where mason gets `v1.37.0` version. So, read the lazy.nvim doc and understand how it's working. Then go ahead and configure it on your setup with whatever the hell you are using.

**Comment by BKR-dev** [comment]
_You need to have custom mason registry from nvim-java when setting up Mason.nvim. It's clearly defined in the lazy.lua. That's where mason gets v1.37.0 version._

That's the problem I want to address. 1.38.0 is in the mason registry and it's all good. If you don't want that fine. But that's a way more complicated way of doing it. Also add it to the docs that you HAVE TO use lazy vim OR that you HAVE to add the registry. "Just install the plugin" clearly isn't working. 

Good luck!

**Comment by s1n7ax** [comment]
> That's the problem I want to address. 

Address it on your own fork you idiot. It's there for a reason.

> Also add it to the docs that you HAVE TO use lazy

It's not saying that you have to use it. It's stating if you are using Lazy this is all have to do. Why don't you start writing steps for all the package managers ever existed so one of the dumb bitches like you comes along and start complain again instead of whining here?
