### ISSUE TITLE
bug: MasonUI is opened and is refreshing EVERY startup of neovim

### ISSUE THREAD

**Issue by BKR-dev** [nvim-java/nvim-java#315]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

nvim v0.10.2

### Operating system/version

macOS 14.7

### Describe the bug

everytime i open neovim when nvim-java is installed, the mason ui is opening and refreshing. 

### Steps To Reproduce

1. install nvim-java
2. install the plugin like the documentation (not using lazy, kickstart or astro)
3. enjoy mason UI being shown every nvim startup

### Expected Behavior

this only happens for the first time, when all dependencies are installed, so it seems that it doesnt handle dependencies being installed and not showing the mason UI. 

for people having the same problem in 

`~/.local/share/nvim/site/pack/packer/start/nvim-java/lua/java/startup/mason-dep.lua`

outcomment line 39 & 40 and you are fine

**Comment by PiotrRaszkowski** [comment]
I think it is related to something else... (or maybe I am wrong). I mean when I successfully added nvim-java mason repo this stopped to happen (without the need to comment out 39&40).

**Comment by BKR-dev** [comment]
@PiotrRaszkowski i have added all repos in my packer config and it still shows up, trying to update and install v1.37.0 as mentioned in my other issue. 

If there is a another mason registry that is working that isn't mentioned in the documentation feel free to make a PR that fixes the missing registry in the documentation

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx
