### ISSUE TITLE
bug: Lombok causes issues when project Java version is > 17.

### ISSUE THREAD

**Issue by nxtkofi** [nvim-java/nvim-java#322]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

 v2.0.1 

### Operating system/version

Linux 6.11.6-arch1-1

### Describe the bug

Hi! I'm having trouble setting nvim-java to work with openjdk 23. I have a spring-boot project that is using version 22. I have installed nvim-java package and lombok stopped throwing but my project doesn't compile now. When I try to compile - every single lombok feature throws an error. I'd like to use openjdk-23 (or at least that 22) and still use lombok nightly and nvim-java. Is there any possibility to make it working? When I uninstalled openjdk-17 (I included jdk.auto_install=false in my lspconfig setup) the project stopped recognizing lombok arguments again.

### Steps To Reproduce

1. Have a spring-boot project that's on openjdk>17 and uses lombok features (such as getters, setters)
2. Try to run the project 
3. Project throws errors

### Expected Behavior

Project should recognize lombok features and use openjdk-23

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java?tab=readme-ov-file#clamp-how-to-use-jdk-xx-version
https://github.com/nvim-java/nvim-java?tab=readme-ov-file#wrench-configuration

```
  jdk = {
    -- install jdk using mason.nvim
    auto_install = true,
  },
```
