### ISSUE TITLE
bug: Cannot install JDTLS in fresh enviroment

### ISSUE THREAD

**Issue by aeropagz** [nvim-java/nvim-java#323]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.2

### Operating system/version

MacOs

### Describe the bug

The jdtls version 1.37.0 is not able to download via mason anymore due a change in the url (I think there is timestamp included). If i download jdtls directly via mason it works but version 1.41.0 is downloaded.

### Steps To Reproduce

1. Create a fresh neovim config with nvim java
2. Open neovim and wait for mason to install jdtls
3. mason will print an failure downloading jdtls

### Expected Behavior

Jdtls should be installed automatically with no errors

**Comment by s1n7ax** [comment]
https://github.com/nvim-java/nvim-java/wiki/Troubleshooting#no_entry-mason-failed-to-install-jdtls---cannot-find-package-xxxxx

**Comment by cristianrgreco** [comment]
I've followed the steps in the wiki but get the same error.  The package it's trying to download doesn't exist, I don't see how changing Mason config helps here: https://download.eclipse.org/jdtls/milestones/1.37.0/jdt-language-server-1.37.0-202410311350.tar.gz

**Comment by aeropagz** [comment]
for it did fix the error. I think if you mess up the mason config certain registries are missed out.

**Comment by cristianrgreco** [comment]
I'm new to nvim and using nvchad so likely i've done something wrong. I found a discussion about this issue which shared some code and it's working for me. This is what I ended up with:

```lua
  {
    "nvim-java/nvim-java",
    lazy = false,
    dependencies = {
      {
        "williamboman/mason.nvim",
        opts = {
          registries = {
            "github:nvim-java/mason-registry",
            "github:mason-org/mason-registry",
          },
        },
      },
    },
    config = function()
      require("java").setup {}
      require("lspconfig").jdtls.setup {}
    end,
  },
```

Go to definition/references isn't working but other things are

**Comment by s1n7ax** [comment]
@nobleach https://github.com/nvim-java/nvim-java/wiki/Troubleshooting#no_entry-mason-failed-to-install-jdtls---cannot-find-package-xxxxx
