### ISSUE TITLE
feature: Opt out of using mason completely

### ISSUE THREAD

**Issue by a-usr** [nvim-java/nvim-java#331]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

There are some cases where you wouldnt want to install your tooling through Mason. For example, I am using nixos, which is incompatible with regular binaries, since it only provides a stub ld. Programs that run on nixos need to be explicitly build for this purpose. Thats why using mason to install tooling like lsp servers doesnt work.

### Describe the solution you'd like

Allow the user to opt out of using mason via the configuration, or replace `require`s to mason with `pcall`s to allow the user to deactivate mason via lazy

### Describe alternatives you've considered

Using nvim-jdtls

**Comment by s1n7ax** [comment]
@a-usr I'm using nixos. You can disable the JDK installation through config. All the other packages works on Nixos since they are running on JVM.
