### ISSUE TITLE
feature: oracle have released a new language server based on netbeans

### ISSUE THREAD

**Issue by kuator** [nvim-java/nvim-java#68]
### Did you check the docs?

- [X] I have read all the docs

### Is your feature request related to a problem? Please describe.

https://inside.java/2023/10/18/announcing-vscode-extension/

### Describe the solution you'd like

I don't know, just wanted to give a heads up

### Describe alternatives you've considered

[]

**Comment by s1n7ax** [comment]
I saw the youtube video of this but didn't know they are using a different LS. I'm going to ignore this for now since there is no reason to change for now but thanks for the heads up. I just tested on jdk-21 and `jdtls` works fine in newer versions.

**Comment by agentgt** [comment]
There are more advantages to the JDT compiler like null analysis which I don't think NetBeans supports (and I have feeling probably will never... ignoring changes to the language itself).

**Comment by s1n7ax** [comment]
Spring boot language servers won't work without jdtls either. Though I still couldn't figureout how to integrate boot-ls

**Comment by s1n7ax** [comment]
Thanks for notifying. Hope someone takes netbeans ls and do neovim integration.
