### ISSUE TITLE
bug: Fail to install java-test using mason

### ISSUE THREAD

**Issue by ryukato** [nvim-java/nvim-java#79]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

macOS sonoma(14.1)

### Describe the bug

I got error message from installation of `java-test`using Mson like below.

```
Downloading file "https://github.com/microsoft/vscode-java-test/releases/download/0.40.1/vscjava.vscode-java-test-0.40.1.vsix"…
spawn: wget failed with exit code 8 and signal 0.
Failed to download file "https://github.com/microsoft/vscode-java-test/releases/download/0.40.1/vscjava.vscode-java-test-0.40.1.vsix".
```

### Steps To Reproduce

Just put configuration as described in https://github.com/nvim-java/nvim-java/wiki/Lazyvim

### Expected Behavior

`java-test` Successfully installed

**Comment by s1n7ax** [comment]
Did you change the order of the mason registries by any chance? registry url from java-nvim should come first.

```
registries = {
   "github:nvim-java/mason-registry",
   "github:mason-org/mason-registry",
}
```

**Comment by Gl00ria** [comment]
@s1n7ax having the same issue

**Comment by s1n7ax** [comment]
@Gl00ria @ryukato any one of you got the configuration in github? repo please

**Comment by s1n7ax** [comment]
You could just create a temp github repo and share me the file. Helps me to debug this easily.

**Comment by Gl00ria** [comment]
@s1n7ax Sure, appreciate your work.

Here is the config [java.lua](https://github.com/Gl00ria/nvim/blob/main/lua/Gl0riVim/plugins/coding/lsp/langs/java.lua)

**Comment by s1n7ax** [comment]
@s1n7ax You are manually setup  the mason.nvim and when you do that you don't pass in the default values nor the registries. 

https://github.com/Gl00ria/nvim/blob/cdae113f292c42d5e97cdd1ee3ca9941b9f1caec/lua/Gl0riVim/plugins/coding/lsp/mason.lua#L38C1-L49C11

Change the config as below,
![image](https://github.com/nvim-java/nvim-java/assets/18459807/94fd6a03-e043-47c8-82fe-62e9f1e6bd01)

Then the package will be installed from the correct registry like a charm.

![image](https://github.com/nvim-java/nvim-java/assets/18459807/f5c829b6-9ec7-493b-9296-e891c5a6d76c)

@ryukato This is probably the same issue you are facing.

**Comment by Gl00ria** [comment]
@s1n7ax perfectly working as expected, appreciate your time & effort.

**Comment by ryukato** [comment]
Sorry for late response and thank you for so quick answer. I made `java-test` installed but getting another error like below. 
```
Failed to setup nvim-java ...l/share/nvim/lazy/mason.nvim/lua/mason-registry/init.lua:80: Cannot find package "jdtls".
```

I appreciate if you take a look at my configs and let me know what I need to do. 
* https://github.com/ryukato/nvim/blob/main/lua/yoonyoul/plugins/nvim-java.lua
* https://github.com/ryukato/nvim/blob/main/lua/yoonyoul/plugins/lsp/mason.lua

**Comment by s1n7ax** [comment]
@ryukato Repository is probably private

**Comment by ryukato** [comment]
@s1n7ax sorry I made it public. :)

**Comment by s1n7ax** [comment]
@ryukato Your repo is little too big to try. So, do you get the registries in the print statement?

https://github.com/ryukato/nvim/blob/32682a4b9a4f2f560b4a60c3a3073de86fe3a3aa/lua/yoonyoul/plugins/lsp/mason.lua#L8

Can you send me the last 10-20 lines from the logs. It's located in `~/.local/share/nvim/nvim-java.log`. I'm not even sure how this is even possible because even if my registry is not there, jdtls should come from the main registry.

**Comment by s1n7ax** [comment]
@ryukato I see. There are multiple issues. 

1. You shouldn't configure nvim-jdtls and nvim-java at the same time.
2. You should manually run mason-lspconfig setup before the any language server setup. (lazyvim does so you should too. Please read the mason-lspconfig plugin for more information on that)
3. I have made a mistake. I'm calling java.setup twice in the configuration. Please change it like below.

Instead of `java.setup`, call `lspconfig.jdtls.setup`

![image](https://github.com/nvim-java/nvim-java/assets/18459807/941c1fd0-5b7e-40d2-b672-96ec7cde8656)

**Comment by s1n7ax** [comment]
Here is the final setup. This works in your config

```lua
return {
	"nvim-java/nvim-java",
	dependencies = {
		"nvim-java/lua-async-await",
		"nvim-java/nvim-java-core",
		"nvim-java/nvim-java-test",
		"nvim-java/nvim-java-dap",
		"MunifTanjim/nui.nvim",
		{
			"neovim/nvim-lspconfig",
			dependencies = { "williamboman/mason-lspconfig.nvim" },
			{
				"williamboman/mason-lspconfig.nvim",
				dependencies = {
					{
						"williamboman/mason.nvim",
						opts = {
							registries = {
								"github:nvim-java/mason-registry",
								"github:mason-org/mason-registry",
							},
						},
					},
				},
			},
		},
		"mfussenegger/nvim-dap",
	},
}
```

```lua
return {
	"williamboman/mason.nvim",
	dependencies = {
		"williamboman/mason-lspconfig.nvim",
		"WhoIsSethDaniel/mason-tool-installer.nvim",
	},
	config = function(_, opts)
		vim.print(opts)
		-- import mason
		local mason = require("mason")

		local conf = vim.tbl_deep_extend("keep", opts, {
			ui = {
				icons = {
					package_installed = "✓",
					package_pending = "➜",
					package_uninstalled = "✗",
				},
			},
		})

		-- enable mason and configure icons
		mason.setup(conf)
		-- import mason-lspconfig
		require("java").setup()
		local mason_lspconfig = require("mason-lspconfig")

		local mason_tool_installer = require("mason-tool-installer")

		mason_lspconfig.setup({
			-- list of servers for mason to install
			ensure_installed = {
				"tsserver",
				"html",
				"lua_ls",
			},
			handlers = {
				["jdtls"] = function()
					require("lspconfig").jdtls.setup({})
				end,
			},
			automatic_installation = true, -- not the same as ensure_installed
		})

		mason_tool_installer.setup({
			ensure_installed = {
				"prettier", -- prettier formatter
				"stylua", -- lua formatter
				"eslint_d", -- js linter
			},
		})
	end,
}
```

**Comment by ryukato** [comment]
Wow! @s1n7ax what a kindness! I really appreciate for your great help.

**Comment by s1n7ax** [comment]
I have added instructions for this issue:
https://github.com/nvim-java/nvim-java/wiki/Q-&-A#no_entry-cannot-find-package-xxxxx
