### ISSUE TITLE
bug: lazyvim config incorrect 

### ISSUE THREAD

**Issue by slav-pilus** [nvim-java/nvim-java#98]
### Did you check docs and existing issues?

- [X] I have read all the plugin docs
- [X] I have searched the existing issues
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.4

### Operating system/version

MacOS 14.2.1

### Describe the bug

Configuration example for LazyVim is not working in its current state.
I suspect there is a difference between OS or some of the dependencies as the working version was removed in the latest commit. 
```
opts = {},
```
is required for mason to pick up the dependencies and install anything.

### Steps To Reproduce

Follow the installation tutorial step by step, after adding configuration to `plugins/java/init.lua` mason is not picking up the dependencies.

### Expected Behavior

The configuration file is working. If there is a difference in how the config should look like between versions or OS it should be called out and given to end user.

**Comment by slav-pilus** [comment]
In case it helps people stuck until this gets sorted here is the full working config:
```lua
return {
  "nvim-java/nvim-java",
  dependencies = {
    "nvim-java/lua-async-await",
    "nvim-java/nvim-java-core",
    "nvim-java/nvim-java-test",
    "nvim-java/nvim-java-dap",
    "MunifTanjim/nui.nvim",
    "neovim/nvim-lspconfig",
    "mfussenegger/nvim-dap",
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "williamboman/mason-lspconfig.nvim",
      opts = {
        handlers = {
          ["jdtls"] = function()
            require("java").setup()
          end,
        },
      },
    },
  },
  opts = {},
}
```

**Comment by s1n7ax** [comment]
@slav-pilus Let me make this clear. You are saying the existing config in wiki doesn't work unless `opts = {}` was added right?

**Comment by slav-pilus** [comment]
Correct @s1n7ax . This line was in place in the wiki but removed by the latest commit. I only presume this was removed for a reason, but this line is necessary for my setup.

**Comment by s1n7ax** [comment]
@slav-pilus It was removed because in the new template it was redundant. Adding `opts={}` will call setup by lazy and we have setup call in the handler as well. So calling it two times is unnecessary. I would like to know the reason. Do you have your updated config on github?

**Comment by slav-pilus** [comment]
here it is @s1n7ax  - https://github.com/slav-pilus/nvimconfig

**Comment by s1n7ax** [comment]
@slav-pilus Your configuration is working as expected. There shouldn't be any platform specific behavior. May be the dependencies are incorrect. Can you try following.

```lua
return {
  "williamboman/mason-lspconfig.nvim",
  dependencies = {
    {
      "williamboman/mason.nvim",
      opts = {
        registries = {
          "github:nvim-java/mason-registry",
          "github:mason-org/mason-registry",
        },
      },
    },
    {
      "nvim-java/nvim-java",
      dependencies = {
        "nvim-java/lua-async-await",
        "nvim-java/nvim-java-core",
        "nvim-java/nvim-java-test",
        "nvim-java/nvim-java-dap",
        "MunifTanjim/nui.nvim",
        "neovim/nvim-lspconfig",
        "mfussenegger/nvim-dap",
      },
    },
  },
  opts = {
    handlers = {
      ["jdtls"] = function()
        require("java").setup()
      end,
    },
  },
}
```

**Comment by s1n7ax** [comment]
@slav-pilus any updates?

**Comment by s1n7ax** [comment]
Closing due to no response

**Comment by JakobEdvardsson** [comment]
> @slav-pilus Your configuration is working as expected. There shouldn't be any platform specific behavior. May be the dependencies are incorrect. Can you try following.
> 
> ```lua
> return {
>   "williamboman/mason-lspconfig.nvim",
>   dependencies = {
>     {
>       "williamboman/mason.nvim",
>       opts = {
>         registries = {
>           "github:nvim-java/mason-registry",
>           "github:mason-org/mason-registry",
>         },
>       },
>     },
>     {
>       "nvim-java/nvim-java",
>       dependencies = {
>         "nvim-java/lua-async-await",
>         "nvim-java/nvim-java-core",
>         "nvim-java/nvim-java-test",
>         "nvim-java/nvim-java-dap",
>         "MunifTanjim/nui.nvim",
>         "neovim/nvim-lspconfig",
>         "mfussenegger/nvim-dap",
>       },
>     },
>   },
>   opts = {
>     handlers = {
>       ["jdtls"] = function()
>         require("java").setup()
>       end,
>     },
>   },
> }
> ```

This does not work on my config either, nothing happens.  @slav-pilus solutions does however work!

**Comment by R-Sandor** [comment]
Yeah I concur that this does not work on Linux, works on MacOS

**Comment by dorudumitru-hh** [comment]
Same here, @slav-pilus solution works.

**Comment by liubilly** [comment]
Same here, @slav-pilus solution works.

cat /etc/os-release
NAME="Nobara Linux"
VERSION="39 (KDE Plasma)"


nvim -version
NVIM v0.9.5
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634

**Comment by s1n7ax** [comment]
I just can't recreate this to debug. If one of you happened to have a Docker setup with neovim config please leave the link here.

**Comment by s1n7ax** [comment]
I've corrected the wiki accordingly. Looks like one of those "works on my machine" situation.
